### ISSUE TITLE
[Bug]: CUBLAS_STATUS_INVALID_VALUE when serving BAGEL-7B-MoT with --quantization fp8 in Docker

### ISSUE THREAD

**Issue by lishunyang12** [vllm-project/vllm-omni#1790]
## Summary

Serving `ByteDance-Seed/BAGEL-7B-MoT` with `--quantization fp8` in the Docker container (based on `vllm/vllm-openai:v0.17.0`) fails during profiling with `CUBLAS_STATUS_INVALID_VALUE`. The root cause is an `LD_LIBRARY_PATH` conflict inherited from the upstream vLLM base Docker image.

**Note:** This is NOT related to the vLLM-OMNI unified quantization framework. The error occurs in the upstream vLLM code path (standard `vllm serve` without `--omni`).

## Environment

- **Docker image**: `vllm/vllm-openai:v0.17.0` (base for `Dockerfile.ci`)
- **Model**: `ByteDance-Seed/BAGEL-7B-MoT`
- **Command**: `vllm serve ByteDance-Seed/BAGEL-7B-MoT --port 8091 --quantization fp8`

## Error

```
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling
cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16BF, lda,
b, CUDA_R_16BF, ldb, &fbeta, c, std::is_same_v<C_Dtype, float> ? CUDA_R_32F
: CUDA_R_16BF, ldc, compute_type, CUBLAS_GEMM_DEFAULT_TENSOR_OP)
```

The error occurs during `profile_run()` → `_dummy_sampler_run()` → `compute_logits()` → `lm_head` unquantized GEMM (`torch.nn.functional.linear`). The fp8-quantized linear layers (smaller dimensions) work fine; only the large `lm_head` matmul (hidden_size=3584 × vocab_size=152064) triggers the error.

## Root Cause

The upstream vLLM v0.17.0 Dockerfile sets:

```dockerfile
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}
```

This causes the system cuBLAS (from CUDA 12.9.1 installed in the container) to **shadow** PyTorch's bundled `nvidia-cublas-cu12` at runtime. The version mismatch causes certain GEMM parameter combinations to be rejected by cuBLAS — specifically large matmuls like the `lm_head` projection — while smaller GEMMs happen to use cuBLAS code paths that are unaffected.

Since `Dockerfile.ci` inherits from `vllm/vllm-openai:v0.17.0`:

```dockerfile
ARG VLLM_BASE_IMAGE=vllm/vllm-openai
ARG VLLM_BASE_TAG=v0.17.0
FROM ${VLLM_BASE_IMAGE}:${VLLM_BASE_TAG}
```

The conflicting `LD_LIBRARY_PATH` is inherited into vLLM-OMNI containers.

## Workaround

```bash
unset LD_LIBRARY_PATH
vllm serve ByteDance-Seed/BAGEL-7B-MoT --port 8091 --quantization fp8
```

## Suggested Fix

Add `ENV LD_LIBRARY_PATH=""` to `Dockerfile.ci` to prevent the inherited conflict:

```dockerfile
FROM ${VLLM_BASE_IMAGE}:${VLLM_BASE_TAG}
ENV LD_LIBRARY_PATH=""
```

Or document the workaround for users running quantized models in Docker.

## Related Issues

- Upstream: vllm-project/vllm#36663 (filed concurrently)
- vllm-project/vllm#35608 — Same error with Qwen3.5-122B, same fix
- vllm-project/vllm#35028 — Same CUBLAS_STATUS_INVALID_VALUE error
- pytorch/pytorch#174949 — cuBLAS version mismatch with PyTorch 2.10

**Comment by Gaohan123** [comment]
@congw729 @tzhouam PTAL

**Comment by congw729** [comment]
Maybe remove `/usr/local/cuda/lib64` from LD_LIBRARY_PATH?

**Comment by lishunyang12** [comment]
Agreed with @congw729 — stripping \ from \ is the right fix. The upstream vllm base image sets it and it shadows PyTorch's bundled cuBLAS. Will put up a one-liner for \.

**Comment by lishunyang12** [comment]
Status update (2026-08-23): the root cause and workaround are identified, but there is still no linked fix PR. Before changing the Docker image, reproduce against the current image and then submit the minimal LD_LIBRARY_PATH cleanup with a BAGEL FP8 smoke test.

**Comment by Gaohan123** [comment]
@lishunyang12 PTAL again. Thanks

**Comment by Gaohan123** [comment]
I tried reproducing this on current main (`e284d907b5554038bef6ab861bdb78b0b99dd5ea`) in a fresh local branch, using the repository's uv environment. I could not reproduce `CUBLAS_STATUS_INVALID_VALUE` in this environment.

Environment: vLLM 0.29.0, PyTorch 2.13.0+cu129 (CUDA 12.9). I refreshed the editable vLLM-Omni installation after checking the current installation instructions. Current `docker/Dockerfile.ci` targets `vllm/vllm-openai:v0.29.0`, whereas the report used v0.17.0.

I ran the original serving command unchanged, inside an exclusive GPU reservation:

```bash
gpu run --gpus 1 --timeout 15m --note issue-1790-reproduction -- bash -c 'source .venv/bin/activate; export HF_HOME=/workspace/models; vllm serve ByteDance-Seed/BAGEL-7B-MoT --port 8091 --quantization fp8'
```

The server loaded the real cached BAGEL weights (HF revision `5019f57d168e5816e8f3f701b17cc816bb7cf24b`), completed profiling/warmup and CUDA graph capture, and started successfully. A `/v1/chat/completions` request with `What is 2 + 2? Answer briefly.`, `temperature=0`, and `max_tokens=32` returned HTTP 200 and `4` (`finish_reason=stop`). The server was then shut down normally.

I also exercised BF16 `torch.nn.functional.linear` with a `[152064, 3584]` weight and batch sizes 1, 16, 128, 256, 512, and 1024. All outputs were finite both with `LD_LIBRARY_PATH` unset and with `/usr/local/nvidia/lib64:/usr/local/cuda/lib64`. `/proc/self/maps` showed the virtual environment's `nvidia/cublas/lib/libcublas.so.12` and `libcublasLt.so.12` in both cases; the real server loaded those same libraries.

**Scope limitation:** this host has no Docker/Podman runtime, so this is a local uv reproduction attempt, not validation of either Docker image. Its system CUDA directory contains cuBLAS 13, which does not shadow the cuBLAS 12 SONAME used by this PyTorch build. Thus the passing result does not disprove the reported conflict in the old image. The upstream v0.29.0 Dockerfile still adds `/usr/local/cuda/lib64` to `LD_LIBRARY_PATH`, so the version bump alone also does not establish that the Docker issue is fixed.

I have not changed Docker library paths or model code based on this non-reproduction. In particular, clearing all of `LD_LIBRARY_PATH` would also discard driver/NVSHMEM-related paths; any image fix should be verified against its actual loaded libraries and the original serving command.

Related tests were run on a separate exclusive GPU, without changing their acceptance criteria:

```bash
gpu run --gpus 1 --timeout 10m --note issue-1790-related-tests -- bash -c 'source .venv/bin/activate; export HF_HOME=/workspace/models; pytest -q tests/quantization/test_quack_fp8_gate.py tests/distributed/omni_connectors/test_bagel_shared_memory_connector.py'
```

Result: **20 passed, 14 deprecation warnings in 546.78s**, including the real-weight BAGEL img2img/text2img reference-pixel checks.

**Comment by Gaohan123** [comment]
I can reopen if needed.
