### ISSUE TITLE
[Bug]:容器里执行nvidia-smi看到两张卡，部署日志只识别一张，什么情况。

### ISSUE THREAD

**Issue by watch-Ultra** [vllm-project/vllm-omni#1906]
### Your current environment

sudo docker run -d \
--name qwen3-omni \
--gpus '"device=1,2"' \
--ipc=host \
--pid=host \
-e NCCL_DEBUG=WARN \
-e CUDA_MODULE_LOADING=LAZY \
-e VLLM_WORKER_MULTIPROC_METHOD=fork \
-e OMP_NUM_THREADS=8 \
-v /xxxx/Qwen3-Omni-30B-A3B-Instruct:/root/models/Qwen3-Omni-30B-A3B-Instruct \
-p 8866:8000 \
vllm/vllm-omni:v0.16.0 \
--model /root/models/Qwen3-Omni-30B-A3B-Instruct \
--served-model-name Qwen3-Omni-30B-A3B-Instruct \
--tensor-parallel-size 2 \
--gpu-memory-utilization 0.95 \
--max-model-len 32768 \
--max-num-seqs 32 \
--enable-prefix-caching \
--limit-mm-per-prompt '{"image":1,"video":4,"audio":8}' \
--seed 1234 \
--host 0.0.0.0 \
--port 8000 \
--enable-auto-tool-choice \
--tool-call-parser hermes

### Your code version

v0.16.0

### 🐛 Describe the bug

admin@ubuntu:~$ sudo docker logs -f qwen3-omni
WARNING 03-16 01:37:26 [envs.py:94] No Flash Attention backend found, using pytorch SDPA implementation
/usr/local/lib/python3.12/dist-packages/pydub/utils.py:300: SyntaxWarning: invalid escape sequence '\('
  m = re.match('([su]([0-9]{1,2})p?) \(([0-9]{1,2}) bit\)$', token)
/usr/local/lib/python3.12/dist-packages/pydub/utils.py:301: SyntaxWarning: invalid escape sequence '\('
  m2 = re.match('([su]([0-9]{1,2})p?)( \(default\))?$', token)
/usr/local/lib/python3.12/dist-packages/pydub/utils.py:310: SyntaxWarning: invalid escape sequence '\('
  elif re.match('(flt)p?( \(default\))?$', token):
/usr/local/lib/python3.12/dist-packages/pydub/utils.py:314: SyntaxWarning: invalid escape sequence '\('
  elif re.match('(dbl)p?( \(default\))?$', token):
WARNING 03-16 01:37:27 [argparse_utils.py:195] With `vllm serve`, you should provide the model as a positional argument or in a config file instead of via the `--model` option. The `--model` option will be removed in v0.13.
INFO 03-16 01:37:31 [logo.py:45]        █     █     █▄   ▄█       ▄????▄ █▄   ▄█ █▄    █ ?█? 
INFO 03-16 01:37:31 [logo.py:45]  ▄▄ ▄█ █     █     █ ?▄? █  ▄▄▄  █    █ █ ?▄? █ █ ?▄  █  █  
INFO 03-16 01:37:31 [logo.py:45]   █▄█? █     █     █     █       █    █ █     █ █   ?▄█  █  
INFO 03-16 01:37:31 [logo.py:45]    ??  ????? ????? ?     ?        ????  ?     ? ?     ? ??? 
INFO 03-16 01:37:31 [logo.py:45] 
(APIServer pid=2834013) INFO 03-16 01:37:31 [utils.py:287] vLLM server version 0.16.0, serving model /root/models/Qwen3-Omni-30B-A3B-Instruct
(APIServer pid=2834013) INFO 03-16 01:37:31 [utils.py:223] non-default args: {'model_tag': '/root/models/Qwen3-Omni-30B-A3B-Instruct', 'host': '0.0.0.0', 'enable_auto_tool_choice': True, 'tool_call_parser': 'hermes', 'model': '/root/models/Qwen3-Omni-30B-A3B-Instruct', 'seed': 1234, 'max_model_len': 32768, 'served_model_name': ['Qwen3-Omni-30B-A3B-Instruct'], 'tensor_parallel_size': 2, 'gpu_memory_utilization': 0.95, 'limit_mm_per_prompt': {'image': 1, 'video': 5, 'audio': 10}, 'max_num_seqs': 10}
(APIServer pid=2834013) INFO 03-16 01:37:31 [omni.py:181] Initializing stages for model: /root/models/Qwen3-Omni-30B-A3B-Instruct
(APIServer pid=2834013) INFO 03-16 01:37:31 [omni.py:313] No omni_master_address provided, defaulting to localhost (127.0.0.1)
(APIServer pid=2834013) The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
(APIServer pid=2834013) Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'interleaved', 'mrope_section', 'mrope_interleaved'}
(APIServer pid=2834013) Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'interleaved', 'mrope_section'}
(APIServer pid=2834013) The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
(APIServer pid=2834013) Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'interleaved', 'mrope_section', 'mrope_interleaved'}
(APIServer pid=2834013) Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'interleaved', 'mrope_section'}
(APIServer pid=2834013) WARNING 03-16 01:37:31 [utils.py:111] Filtered out 1 callable object(s) from base_engine_args that are not compatible with OmegaConf: ['dispatch_function']. 
(APIServer pid=2834013) INFO 03-16 01:37:31 [initialization.py:251] Auto-configuring SharedMemoryConnector for edge ('0', '1')
(APIServer pid=2834013) INFO 03-16 01:37:31 [initialization.py:251] Auto-configuring SharedMemoryConnector for edge ('1', '2')
(APIServer pid=2834013) INFO 03-16 01:37:31 [initialization.py:270] Loaded OmniTransferConfig with 2 connector configurations
(APIServer pid=2834013) INFO 03-16 01:37:31 [factory.py:46] Created connector: SharedMemoryConnector
(APIServer pid=2834013) INFO 03-16 01:37:31 [initialization.py:60] Created connector for 0 -> 1: SharedMemoryConnector
(APIServer pid=2834013) INFO 03-16 01:37:31 [factory.py:46] Created connector: SharedMemoryConnector
(APIServer pid=2834013) INFO 03-16 01:37:31 [initialization.py:60] Created connector for 1 -> 2: SharedMemoryConnector
(APIServer pid=2834013) INFO 03-16 01:37:31 [omni.py:347] [AsyncOrchestrator] Loaded 3 stages
[Stage-1] WARNING 03-16 01:37:42 [envs.py:94] No Flash Attention backend found, using pytorch SDPA implementation
[Stage-1] INFO 03-16 01:37:42 [omni_stage.py:1132] [Stage-1] ZMQ transport detected; disabling SHM IPC (shm_threshold_bytes set to maxsize)
[Stage-1] INFO 03-16 01:37:42 [initialization.py:324] [Stage-1] Initializing OmniConnectors with config keys: ['from_stage_0']
[Stage-1] INFO 03-16 01:37:42 [factory.py:46] Created connector: SharedMemoryConnector
[Stage-1] INFO 03-16 01:37:42 [initialization.py:60] Created connector for 0 -> 1: SharedMemoryConnector
[Stage-1] INFO 03-16 01:37:42 [omni_stage.py:79] NVML process-scoped memory available and PID host is available — concurrent init is safe, skipping locks
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'mrope_interleaved', 'interleaved', 'mrope_section'}
Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'interleaved', 'mrope_section'}
[Stage-0] WARNING 03-16 01:37:43 [envs.py:94] No Flash Attention backend found, using pytorch SDPA implementation
[Stage-0] INFO 03-16 01:37:43 [omni_stage.py:1132] [Stage-0] ZMQ transport detected; disabling SHM IPC (shm_threshold_bytes set to maxsize)
[Stage-0] INFO 03-16 01:37:43 [initialization.py:324] [Stage-0] Initializing OmniConnectors with config keys: ['to_stage_1']
[Stage-0] INFO 03-16 01:37:43 [omni_stage.py:79] NVML process-scoped memory available and PID host is available — concurrent init is safe, skipping locks
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'interleaved', 'mrope_section', 'mrope_interleaved'}
Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'interleaved', 'mrope_section'}
[Stage-2] WARNING 03-16 01:37:53 [envs.py:94] No Flash Attention backend found, using pytorch SDPA implementation
(APIServer pid=2834013) INFO 03-16 01:37:54 [omni.py:458] [AsyncOrchestrator] Waiting for 3 stages to initialize (timeout: 600s)
[Stage-2] INFO 03-16 01:37:54 [omni_stage.py:1132] [Stage-2] ZMQ transport detected; disabling SHM IPC (shm_threshold_bytes set to maxsize)
[Stage-2] INFO 03-16 01:37:54 [initialization.py:324] [Stage-2] Initializing OmniConnectors with config keys: ['from_stage_1']
[Stage-2] INFO 03-16 01:37:54 [factory.py:46] Created connector: SharedMemoryConnector
[Stage-2] INFO 03-16 01:37:54 [initialization.py:60] Created connector for 1 -> 2: SharedMemoryConnector
[Stage-2] INFO 03-16 01:37:54 [omni_stage.py:79] NVML process-scoped memory available and PID host is available — concurrent init is safe, skipping locks
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'mrope_interleaved', 'interleaved', 'mrope_section'}
Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'interleaved', 'mrope_section'}
[Stage-1] INFO 03-16 01:37:54 [model.py:529] Resolved architecture: Qwen3OmniMoeForConditionalGeneration
[Stage-1] INFO 03-16 01:37:54 [model.py:1549] Using max model len 32768
[Stage-1] INFO 03-16 01:37:54 [model.py:1549] Using max model len 32768
[Stage-1] INFO 03-16 01:37:54 [scheduler.py:224] Chunked prefill is enabled with max_num_batched_tokens=32768.
[Stage-1] INFO 03-16 01:37:54 [vllm.py:689] Asynchronous scheduling is enabled.
[Stage-0] INFO 03-16 01:37:55 [model.py:529] Resolved architecture: Qwen3OmniMoeForConditionalGeneration
[Stage-0] INFO 03-16 01:37:55 [model.py:1549] Using max model len 32768
[Stage-0] INFO 03-16 01:37:55 [scheduler.py:224] Chunked prefill is enabled with max_num_batched_tokens=32768.
[Stage-0] INFO 03-16 01:37:55 [vllm.py:689] Asynchronous scheduling is enabled.
The image processor of type `Qwen2VLImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`. Note that this behavior will be extended to all models in a future release.
The image processor of type `Qwen2VLImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`. Note that this behavior will be extended to all models in a future release.
[Stage-2] INFO 03-16 01:38:05 [model.py:529] Resolved architecture: Qwen3OmniMoeForConditionalGeneration
[Stage-2] INFO 03-16 01:38:05 [model.py:1549] Using max model len 32768
[Stage-2] INFO 03-16 01:38:05 [scheduler.py:224] Chunked prefill is enabled with max_num_batched_tokens=1000000.
[Stage-2] INFO 03-16 01:38:05 [vllm.py:689] Asynchronous scheduling is disabled.
[Stage-2] WARNING 03-16 01:38:05 [vllm.py:727] Enforce eager set, overriding optimization level to -O0
[Stage-2] INFO 03-16 01:38:05 [vllm.py:845] Cudagraph is disabled under eager mode
The image processor of type `Qwen2VLImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`. Note that this behavior will be extended to all models in a future release.
[Stage-1] WARNING 03-16 01:38:10 [envs.py:94] No Flash Attention backend found, using pytorch SDPA implementation
[Stage-0] WARNING 03-16 01:38:10 [envs.py:94] No Flash Attention backend found, using pytorch SDPA implementation
(EngineCore_DP0 pid=2836668) [Stage-1] INFO 03-16 01:38:11 [core.py:97] Initializing a V1 LLM engine (v0.16.0) with config: model='/root/models/Qwen3-Omni-30B-A3B-Instruct', speculative_config=None, tokenizer='/root/models/Qwen3-Omni-30B-A3B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=1234, served_model_name=Qwen3-Omni-30B-A3B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [32768], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': 128, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore_DP0 pid=2836668) [Stage-1] WARNING 03-16 01:38:11 [multiproc_executor.py:921] Reducing Torch parallelism from 32 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
(EngineCore_DP0 pid=2836741) [Stage-0] INFO 03-16 01:38:11 [core.py:97] Initializing a V1 LLM engine (v0.16.0) with config: model='/root/models/Qwen3-Omni-30B-A3B-Instruct', speculative_config=None, tokenizer='/root/models/Qwen3-Omni-30B-A3B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=1234, served_model_name=Qwen3-Omni-30B-A3B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [32768], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': 128, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore_DP0 pid=2836741) [Stage-0] WARNING 03-16 01:38:11 [multiproc_executor.py:921] Reducing Torch parallelism from 32 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
[Stage-0] WARNING 03-16 01:38:20 [envs.py:94] No Flash Attention backend found, using pytorch SDPA implementation
[Stage-1] WARNING 03-16 01:38:20 [envs.py:94] No Flash Attention backend found, using pytorch SDPA implementation
[Stage-1] WARNING 03-16 01:38:21 [envs.py:94] No Flash Attention backend found, using pytorch SDPA implementation
[Stage-2] WARNING 03-16 01:38:21 [envs.py:94] No Flash Attention backend found, using pytorch SDPA implementation
(EngineCore_DP0 pid=2837290) [Stage-2] INFO 03-16 01:38:21 [core.py:97] Initializing a V1 LLM engine (v0.16.0) with config: model='/root/models/Qwen3-Omni-30B-A3B-Instruct', speculative_config=None, tokenizer='/root/models/Qwen3-Omni-30B-A3B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=1234, served_model_name=Qwen3-Omni-30B-A3B-Instruct, enable_prefix_caching=False, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'splitting_ops': [], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [1000000], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': [], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': 0, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore_DP0 pid=2837290) [Stage-2] WARNING 03-16 01:38:21 [multiproc_executor.py:921] Reducing Torch parallelism from 32 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
[Stage-0] INFO 03-16 01:38:21 [parallel_state.py:1234] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://127.0.0.1:54733 backend=nccl
[Stage-0] INFO 03-16 01:38:21 [parallel_state.py:1445] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank 0
[Stage-1] ERROR 03-16 01:38:21 [multiproc_executor.py:783] WorkerProc failed to start.
[Stage-1] ERROR 03-16 01:38:21 [multiproc_executor.py:783] Traceback (most recent call last):
[Stage-1] ERROR 03-16 01:38:21 [multiproc_executor.py:783]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 754, in worker_main
[Stage-1] ERROR 03-16 01:38:21 [multiproc_executor.py:783]     worker = WorkerProc(*args, **kwargs)
[Stage-1] ERROR 03-16 01:38:21 [multiproc_executor.py:783]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Stage-1] ERROR 03-16 01:38:21 [multiproc_executor.py:783]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 571, in __init__
[Stage-1] ERROR 03-16 01:38:21 [multiproc_executor.py:783]     self.worker.init_device()
[Stage-1] ERROR 03-16 01:38:21 [multiproc_executor.py:783]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/worker_base.py", line 322, in init_device
[Stage-1] ERROR 03-16 01:38:21 [multiproc_executor.py:783]     self.worker.init_device()  # type: ignore
[Stage-1] ERROR 03-16 01:38:21 [multiproc_executor.py:783]     ^^^^^^^^^^^^^^^^^^^^^^^^^
[Stage-1] ERROR 03-16 01:38:21 [multiproc_executor.py:783]   File "/usr/local/lib/python3.12/dist-packages/vllm_omni/worker/gpu_ar_worker.py", line 51, in init_device
[Stage-1] ERROR 03-16 01:38:21 [multiproc_executor.py:783]     assert self.local_rank < torch.cuda.device_count(), (
[Stage-1] ERROR 03-16 01:38:21 [multiproc_executor.py:783]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Stage-1] ERROR 03-16 01:38:21 [multiproc_executor.py:783] AssertionError: DP adjusted local rank 1 is out of bounds. 
[Stage-1] INFO 03-16 01:38:21 [multiproc_executor.py:732] Parent process exited, terminating worker
[Stage-1] INFO 03-16 01:38:22 [multiproc_executor.py:732] Parent process exited, terminating worker
The image processor of type `Qwen2VLImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`. Note that this behavior will be extended to all models in a future release.
[Stage-1] ERROR 03-16 01:38:22 [multiproc_executor.py:783] WorkerProc failed to start.
[Stage-1] ERROR 03-16 01:38:22 [multiproc_executor.py:783] Traceback (most recent call last):
[Stage-1] ERROR 03-16 01:38:22 [multiproc_executor.py:783]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 754, in worker_main
[Stage-1] ERROR 03-16 01:38:22 [multiproc_executor.py:783]     worker = WorkerProc(*args, **kwargs)
[Stage-1] ERROR 03-16 01:38:22 [multiproc_executor.py:783]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Stage-1] ERROR 03-16 01:38:22 [multiproc_executor.py:783]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 571, in __init__
[Stage-1] ERROR 03-16 01:38:22 [multiproc_executor.py:783]     self.worker.init_device()
[Stage-1] ERROR 03-16 01:38:22 [multiproc_executor.py:783]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/worker_base.py", line 322, in init_device
[Stage-1] ERROR 03-16 01:38:22 [multiproc_executor.py:783]     self.worker.init_device()  # type: ignore
[Stage-1] ERROR 03-16 01:38:22 [multiproc_executor.py:783]     ^^^^^^^^^^^^^^^^^^^^^^^^^
[Stage-1] ERROR 03-16 01:38:22 [multiproc_executor.py:783]   File "/usr/local/lib/python3.12/dist-packages/vllm_omni/worker/gpu_ar_worker.py", line 55, in init_device
[Stage-1] ERROR 03-16 01:38:22 [multiproc_executor.py:783]     assert self.parallel_config.local_world_size <= visible_device_count, (
[Stage-1] ERROR 03-16 01:38:22 [multiproc_executor.py:783]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Stage-1] ERROR 03-16 01:38:22 [multiproc_executor.py:783] AssertionError: local_world_size (2) must be less than or equal to the number of visible devices (1).
(EngineCore_DP0 pid=2836668) [Stage-1] ERROR 03-16 01:38:24 [core.py:1006] EngineCore failed to start.
(EngineCore_DP0 pid=2836668) [Stage-1] ERROR 03-16 01:38:24 [core.py:1006] Traceback (most recent call last):
(EngineCore_DP0 pid=2836668) [Stage-1] ERROR 03-16 01:38:24 [core.py:1006]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 996, in run_engine_core
(EngineCore_DP0 pid=2836668) [Stage-1] ERROR 03-16 01:38:24 [core.py:1006]     engine_core = EngineCoreProc(*args, engine_index=dp_rank, **kwargs)
(EngineCore_DP0 pid=2836668) [Stage-1] ERROR 03-16 01:38:24 [core.py:1006]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=2836668) [Stage-1] ERROR 03-16 01:38:24 [core.py:1006]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 740, in __init__
(EngineCore_DP0 pid=2836668) [Stage-1] ERROR 03-16 01:38:24 [core.py:1006]     super().__init__(
(EngineCore_DP0 pid=2836668) [Stage-1] ERROR 03-16 01:38:24 [core.py:1006]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 106, in __init__
(EngineCore_DP0 pid=2836668) [Stage-1] ERROR 03-16 01:38:24 [core.py:1006]     self.model_executor = executor_class(vllm_config)
(EngineCore_DP0 pid=2836668) [Stage-1] ERROR 03-16 01:38:24 [core.py:1006]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=2836668) [Stage-1] ERROR 03-16 01:38:24 [core.py:1006]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 98, in __init__
(EngineCore_DP0 pid=2836668) [Stage-1] ERROR 03-16 01:38:24 [core.py:1006]     super().__init__(vllm_config)
(EngineCore_DP0 pid=2836668) [Stage-1] ERROR 03-16 01:38:24 [core.py:1006]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/abstract.py", line 103, in __init__
(EngineCore_DP0 pid=2836668) [Stage-1] ERROR 03-16 01:38:24 [core.py:1006]     self._init_executor()
(EngineCore_DP0 pid=2836668) [Stage-1] ERROR 03-16 01:38:24 [core.py:1006]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 166, in _init_executor
(EngineCore_DP0 pid=2836668) [Stage-1] ERROR 03-16 01:38:24 [core.py:1006]     self.workers = WorkerProc.wait_for_ready(unready_workers)
(EngineCore_DP0 pid=2836668) [Stage-1] ERROR 03-16 01:38:24 [core.py:1006]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=2836668) [Stage-1] ERROR 03-16 01:38:24 [core.py:1006]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 680, in wait_for_ready
(EngineCore_DP0 pid=2836668) [Stage-1] ERROR 03-16 01:38:24 [core.py:1006]     raise e from None
(EngineCore_DP0 pid=2836668) [Stage-1] ERROR 03-16 01:38:24 [core.py:1006] Exception: WorkerProc initialization failed due to an exception in a background process. See stack trace for root cause.
(EngineCore_DP0 pid=2836668) Process EngineCore_DP0:
(EngineCore_DP0 pid=2836668) Traceback (most recent call last):
(EngineCore_DP0 pid=2836668)   File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
(EngineCore_DP0 pid=2836668)     self.run()
(EngineCore_DP0 pid=2836668)   File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
(EngineCore_DP0 pid=2836668)     self._target(*self._args, **self._kwargs)
(EngineCore_DP0 pid=2836668)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 1010, in run_engine_core
(EngineCore_DP0 pid=2836668)     raise e
(EngineCore_DP0 pid=2836668)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 996, in run_engine_core
(EngineCore_DP0 pid=2836668)     engine_core = EngineCoreProc(*args, engine_index=dp_rank, **kwargs)
(EngineCore_DP0 pid=2836668)                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=2836668)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 740, in __init__
(EngineCore_DP0 pid=2836668)     super().__init__(
(EngineCore_DP0 pid=2836668)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 106, in __init__
(EngineCore_DP0 pid=2836668)     self.model_executor = executor_class(vllm_config)
(EngineCore_DP0 pid=2836668)                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=2836668)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 98, in __init__
(EngineCore_DP0 pid=2836668)     super().__init__(vllm_config)
(EngineCore_DP0 pid=2836668)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/abstract.py", line 103, in __init__
(EngineCore_DP0 pid=2836668)     self._init_executor()
(EngineCore_DP0 pid=2836668)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 166, in _init_executor
(EngineCore_DP0 pid=2836668)     self.workers = WorkerProc.wait_for_ready(unready_workers)
(EngineCore_DP0 pid=2836668)                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=2836668)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 680, in wait_for_ready
(EngineCore_DP0 pid=2836668)     raise e from None
(EngineCore_DP0 pid=2836668) Exception: WorkerProc initialization failed due to an exception in a background process. See stack trace for root cause.
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/entrypoints/omni_stage.py", line 1075, in _stage_worker_async_entry
    asyncio.run(_stage_worker_async(model, stage_payload, in_q, out_q, batch_timeout, stage_init_timeout))
  File "/usr/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/entrypoints/omni_stage.py", line 1206, in _stage_worker_async
    stage_engine = AsyncOmniLLM.from_vllm_config(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/utils/func_utils.py", line 116, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/entrypoints/async_omni_llm.py", line 208, in from_vllm_config
    return cls(
           ^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/entrypoints/async_omni_llm.py", line 137, in __init__
    self.engine_core = EngineCoreClient.make_async_mp_client(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 124, in make_async_mp_client
    return AsyncMPClient(*client_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 835, in __init__
    super().__init__(
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 490, in __init__
    with launch_core_engines(vllm_config, executor_class, log_stats) as (
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/utils.py", line 925, in launch_core_engines
    wait_for_engine_startup(
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/utils.py", line 984, in wait_for_engine_startup
    raise RuntimeError(
RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
(Worker pid=2837241) [Stage-0] INFO 03-16 01:38:27 [gpu_model_runner.py:4124] Starting to load model /root/models/Qwen3-Omni-30B-A3B-Instruct...
(Worker pid=2837241) [Stage-0] INFO 03-16 01:38:27 [vllm.py:689] Asynchronous scheduling is enabled.
(Worker pid=2837241) [Stage-0] INFO 03-16 01:38:27 [mm_encoder_attention.py:77] Using AttentionBackendEnum.FLASH_ATTN for MMEncoderAttention.
[Stage-2] WARNING 03-16 01:38:31 [envs.py:94] No Flash Attention backend found, using pytorch SDPA implementation
[Stage-2] WARNING 03-16 01:38:31 [envs.py:94] No Flash Attention backend found, using pytorch SDPA implementation
[Stage-2] ERROR 03-16 01:38:32 [multiproc_executor.py:783] WorkerProc failed to start.
[Stage-2] ERROR 03-16 01:38:32 [multiproc_executor.py:783] Traceback (most recent call last):
[Stage-2] ERROR 03-16 01:38:32 [multiproc_executor.py:783]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 754, in worker_main
[Stage-2] ERROR 03-16 01:38:32 [multiproc_executor.py:783]     worker = WorkerProc(*args, **kwargs)
[Stage-2] ERROR 03-16 01:38:32 [multiproc_executor.py:783]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Stage-2] ERROR 03-16 01:38:32 [multiproc_executor.py:783]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 571, in __init__
[Stage-2] ERROR 03-16 01:38:32 [multiproc_executor.py:783]     self.worker.init_device()
[Stage-2] ERROR 03-16 01:38:32 [multiproc_executor.py:783]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/worker_base.py", line 322, in init_device
[Stage-2] ERROR 03-16 01:38:32 [multiproc_executor.py:783]     self.worker.init_device()  # type: ignore
[Stage-2] ERROR 03-16 01:38:32 [multiproc_executor.py:783]     ^^^^^^^^^^^^^^^^^^^^^^^^^
[Stage-2] ERROR 03-16 01:38:32 [multiproc_executor.py:783]   File "/usr/local/lib/python3.12/dist-packages/vllm_omni/worker/gpu_generation_worker.py", line 51, in init_device
[Stage-2] ERROR 03-16 01:38:32 [multiproc_executor.py:783]     assert self.local_rank < torch.cuda.device_count(), (
[Stage-2] ERROR 03-16 01:38:32 [multiproc_executor.py:783]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Stage-2] ERROR 03-16 01:38:32 [multiproc_executor.py:783] AssertionError: DP adjusted local rank 1 is out of bounds. 
[Stage-2] INFO 03-16 01:38:32 [multiproc_executor.py:732] Parent process exited, terminating worker
[Stage-2] INFO 03-16 01:38:32 [multiproc_executor.py:732] Parent process exited, terminating worker
[Stage-2] ERROR 03-16 01:38:33 [multiproc_executor.py:783] WorkerProc failed to start.
[Stage-2] ERROR 03-16 01:38:33 [multiproc_executor.py:783] Traceback (most recent call last):
[Stage-2] ERROR 03-16 01:38:33 [multiproc_executor.py:783]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 754, in worker_main
[Stage-2] ERROR 03-16 01:38:33 [multiproc_executor.py:783]     worker = WorkerProc(*args, **kwargs)
[Stage-2] ERROR 03-16 01:38:33 [multiproc_executor.py:783]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Stage-2] ERROR 03-16 01:38:33 [multiproc_executor.py:783]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 571, in __init__
[Stage-2] ERROR 03-16 01:38:33 [multiproc_executor.py:783]     self.worker.init_device()
[Stage-2] ERROR 03-16 01:38:33 [multiproc_executor.py:783]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/worker_base.py", line 322, in init_device
[Stage-2] ERROR 03-16 01:38:33 [multiproc_executor.py:783]     self.worker.init_device()  # type: ignore
[Stage-2] ERROR 03-16 01:38:33 [multiproc_executor.py:783]     ^^^^^^^^^^^^^^^^^^^^^^^^^
[Stage-2] ERROR 03-16 01:38:33 [multiproc_executor.py:783]   File "/usr/local/lib/python3.12/dist-packages/vllm_omni/worker/gpu_generation_worker.py", line 55, in init_device
[Stage-2] ERROR 03-16 01:38:33 [multiproc_executor.py:783]     assert self.parallel_config.local_world_size <= visible_device_count, (
[Stage-2] ERROR 03-16 01:38:33 [multiproc_executor.py:783]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Stage-2] ERROR 03-16 01:38:33 [multiproc_executor.py:783] AssertionError: local_world_size (2) must be less than or equal to the number of visible devices (1).
(EngineCore_DP0 pid=2837290) [Stage-2] ERROR 03-16 01:38:34 [core.py:1006] EngineCore failed to start.
(EngineCore_DP0 pid=2837290) [Stage-2] ERROR 03-16 01:38:34 [core.py:1006] Traceback (most recent call last):
(EngineCore_DP0 pid=2837290) [Stage-2] ERROR 03-16 01:38:34 [core.py:1006]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 996, in run_engine_core
(EngineCore_DP0 pid=2837290) [Stage-2] ERROR 03-16 01:38:34 [core.py:1006]     engine_core = EngineCoreProc(*args, engine_index=dp_rank, **kwargs)
(EngineCore_DP0 pid=2837290) [Stage-2] ERROR 03-16 01:38:34 [core.py:1006]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=2837290) [Stage-2] ERROR 03-16 01:38:34 [core.py:1006]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 740, in __init__
(EngineCore_DP0 pid=2837290) [Stage-2] ERROR 03-16 01:38:34 [core.py:1006]     super().__init__(
(EngineCore_DP0 pid=2837290) [Stage-2] ERROR 03-16 01:38:34 [core.py:1006]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 106, in __init__
(EngineCore_DP0 pid=2837290) [Stage-2] ERROR 03-16 01:38:34 [core.py:1006]     self.model_executor = executor_class(vllm_config)
(EngineCore_DP0 pid=2837290) [Stage-2] ERROR 03-16 01:38:34 [core.py:1006]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=2837290) [Stage-2] ERROR 03-16 01:38:34 [core.py:1006]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 98, in __init__
(EngineCore_DP0 pid=2837290) [Stage-2] ERROR 03-16 01:38:34 [core.py:1006]     super().__init__(vllm_config)
(EngineCore_DP0 pid=2837290) Process EngineCore_DP0:
(EngineCore_DP0 pid=2837290) [Stage-2] ERROR 03-16 01:38:34 [core.py:1006]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/abstract.py", line 103, in __init__
(EngineCore_DP0 pid=2837290) [Stage-2] ERROR 03-16 01:38:34 [core.py:1006]     self._init_executor()
(EngineCore_DP0 pid=2837290) [Stage-2] ERROR 03-16 01:38:34 [core.py:1006]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 166, in _init_executor
(EngineCore_DP0 pid=2837290) [Stage-2] ERROR 03-16 01:38:34 [core.py:1006]     self.workers = WorkerProc.wait_for_ready(unready_workers)
(EngineCore_DP0 pid=2837290) [Stage-2] ERROR 03-16 01:38:34 [core.py:1006]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=2837290) [Stage-2] ERROR 03-16 01:38:34 [core.py:1006]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 680, in wait_for_ready
(EngineCore_DP0 pid=2837290) [Stage-2] ERROR 03-16 01:38:34 [core.py:1006]     raise e from None
(EngineCore_DP0 pid=2837290) [Stage-2] ERROR 03-16 01:38:34 [core.py:1006] Exception: WorkerProc initialization failed due to an exception in a background process. See stack trace for root cause.
(EngineCore_DP0 pid=2837290) Traceback (most recent call last):
(EngineCore_DP0 pid=2837290)   File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
(EngineCore_DP0 pid=2837290)     self.run()
(EngineCore_DP0 pid=2837290)   File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
(EngineCore_DP0 pid=2837290)     self._target(*self._args, **self._kwargs)
(EngineCore_DP0 pid=2837290)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 1010, in run_engine_core
(EngineCore_DP0 pid=2837290)     raise e
(EngineCore_DP0 pid=2837290)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 996, in run_engine_core
(EngineCore_DP0 pid=2837290)     engine_core = EngineCoreProc(*args, engine_index=dp_rank, **kwargs)
(EngineCore_DP0 pid=2837290)                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=2837290)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 740, in __init__
(EngineCore_DP0 pid=2837290)     super().__init__(
(EngineCore_DP0 pid=2837290)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 106, in __init__
(EngineCore_DP0 pid=2837290)     self.model_executor = executor_class(vllm_config)
(EngineCore_DP0 pid=2837290)                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=2837290)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 98, in __init__
(EngineCore_DP0 pid=2837290)     super().__init__(vllm_config)
(EngineCore_DP0 pid=2837290)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/abstract.py", line 103, in __init__
(EngineCore_DP0 pid=2837290)     self._init_executor()
(EngineCore_DP0 pid=2837290)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 166, in _init_executor
(EngineCore_DP0 pid=2837290)     self.workers = WorkerProc.wait_for_ready(unready_workers)
(EngineCore_DP0 pid=2837290)                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=2837290)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 680, in wait_for_ready
(EngineCore_DP0 pid=2837290)     raise e from None
(EngineCore_DP0 pid=2837290) Exception: WorkerProc initialization failed due to an exception in a background process. See stack trace for root cause.
Process SpawnProcess-3:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/entrypoints/omni_stage.py", line 1075, in _stage_worker_async_entry
    asyncio.run(_stage_worker_async(model, stage_payload, in_q, out_q, batch_timeout, stage_init_timeout))
  File "/usr/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/entrypoints/omni_stage.py", line 1206, in _stage_worker_async
    stage_engine = AsyncOmniLLM.from_vllm_config(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/utils/func_utils.py", line 116, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/entrypoints/async_omni_llm.py", line 208, in from_vllm_config
    return cls(
           ^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/entrypoints/async_omni_llm.py", line 137, in __init__
    self.engine_core = EngineCoreClient.make_async_mp_client(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 124, in make_async_mp_client
    return AsyncMPClient(*client_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 835, in __init__
    super().__init__(
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 490, in __init__
    with launch_core_engines(vllm_config, executor_class, log_stats) as (
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/utils.py", line 925, in launch_core_engines
    wait_for_engine_startup(
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/utils.py", line 984, in wait_for_engine_startup
    raise RuntimeError(
RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://vllm-omni.readthedocs.io), which can answer lots of frequently asked questions.

**Comment by watch-Ultra** [comment]
部署qwen3-omni-A3b模型

**Comment by Dnoob** [comment]
Hi, I've reproduced this issue and have a fix ready. Could you assign this to me? I'll submit a PR shortly.
**Workaround:** Remove `--tensor-parallel-size 2`. The default config already distributes across 2 GPUs.

**Comment by Gaohan123** [comment]
> Hi, I've reproduced this issue and have a fix ready. Could you assign this to me? I'll submit a PR shortly.
> **Workaround:** Remove `--tensor-parallel-size 2`. The default config already distributes across 2 GPUs.

Thanks for your contribution!

**Comment by watch-Ultra** [comment]
> Hi, I've reproduced this issue and have a fix ready. Could you assign this to me? I'll submit a PR shortly. **Workaround:** Remove `--tensor-parallel-size 2`. The default config already distributes across 2 GPUs.

还是不行，我现在用的vllm=0.14.0能部署成功和正常使用，用vllm0.16.0完全不行，参数设置都没变，0.16.0版本CUDA out of memory. 模型没加载成功。

**Comment by Dnoob** [comment]
> 还是不行，我现在用的vllm=0.14.0能部署成功和正常使用，用vllm0.16.0完全不行，参数设置都没变，0.16.0版本CUDA out of memory. 模型没加载成功。

Could you provide the following so we can investigate further:
1. Your GPU model and VRAM size (output of `nvidia-smi`)
2. The full startup command you used with v0.14.0

**Comment by watch-Ultra** [comment]
> > 还是不行，我现在用的vllm=0.14.0能部署成功和正常使用，用vllm0.16.0完全不行，参数设置都没变，0.16.0版本CUDA out of memory. 模型没加载成功。
> 
> 请您提供以下信息，以便我们进一步调查：
> 
> 1. 您的GPU型号和显存大小（输出结果`nvidia-smi`）
> 2. 您使用 v0.14.0 版本启动时使用的完整启动命令

<img width="1149" height="664" alt="Image" src="https://github.com/user-attachments/assets/ef35fe41-092f-48f8-b9ff-bcfbaf22be5a" />                                                                                                                                                                                                                         sudo docker run -d --gpus '"device=1,2"' --restart always --shm-size=32g -e NVIDIA_VISIBLE_DEVICES=1,2  -e TORCH_CUDA_ARCH_LIST="8.6+PTX"  -e CUDA_MODULE_LOADING=LAZY   -e NCCL_DEBUG=INFO --name qwen3-omni  -v /xxxx/Qwen3-Omni-30B-A3B-Instruct:/root/models/Qwen3-Omni-30B-A3B-Instruct  -p 8866:8000  vllm/vllm-omni:v0.14.0 python -m vllm.entrypoints.openai.api_server  --model /root/models/Qwen3-Omni-30B-A3B-Instruct  --tensor-parallel-size 2 --gpu-memory-utilization 0.92 --max-num-seqs 8 --max-model-len 65536 --limit-mm-per-prompt '{"image":10,"video":10,"audio":10}' --seed 1234 --served-model-name Qwen3-Omni-30B-A3B-Instruct --host 0.0.0.0 --port 8000 --enable-auto-tool-choice --tool-call-parser hermes

**Comment by watch-Ultra** [comment]
> > > 还是不行，我现在用的vllm=0.14.0能部署成功和正常使用，用vllm0.16.0完全不行，参数设置都没变，0.16.0版本CUDA out of memory. 模型没加载成功。
> > 
> > 
> > 请您提供以下信息，以便我们进一步调查：
> > 
> > 1. 您的GPU型号和显存大小（输出结果`nvidia-smi`）
> > 2. 您使用v0.14.0 版本启动时使用的完整启动命令
> 
> <img alt="图像" width="1149" height="664" src="https://private-user-images.githubusercontent.com/177522180/564615718-ef35fe41-092f-48f8-b9ff-bcfbaf22be5a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzM3MzQyMTcsIm5iZiI6MTc3MzczMzkxNywicGF0aCI6Ii8xNzc1MjIxODAvNTY0NjE1NzE4LWVmMzVmZTQxLTA5MmYtNDhmOC1iOWZmLWJjZmJhZjIyYmU1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDMxN1QwNzUxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjg2YzUxODNkNGY5OGRmYTllNTM0OTg2YTFlMTQ0OGZkMGRkOGRmZjM0MWRmOTc4NTYyZjk4ODVkOTdmNDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2zqseKag82TaRnYW9aVc76XKBR-G2yNWft9phYtzTKM"> sudo docker run -d --gpus '"device=1,2"' --restart always --shm-size=32g -e NVIDIA_VISIBLE_DEVICES=1,2 -e TORCH_CUDA_ARCH_LIST="8.6+PTX" -e CUDA_MODULE_LOADING=LAZY -e NCCL_DEBUG=INFO --name qwen3-omni -v /xxxx/Qwen3-Omni-30B-A3B-Instruct:/root/models/Qwen3-Omni-30B-A3B-Instruct -p 8866:8000 vllm/vllm-omni:v0.14.0 python -m vllm.entrypoints.openai.api_server --model /root/models/Qwen3-Omni-30B-A3B-Instruct --tensor-parallel-size 2 --gpu-memory-utilization 0.92 --max-num-seqs 8 --max-model-len 65536 --limit-mm-per-prompt '{"image":10,"video":10,"audio":10}' --seed 1234 --served-model-name Qwen3-Omni-30B-A3B-Instruct --host 0.0.0.0 --port 8000 --enable-auto-tool-choice --tool-call-parser hermes

<img width="3112" height="1926" alt="Image" src="https://github.com/user-attachments/assets/410d3ae4-5239-4e2b-ba3d-ec13b58d974d" />

**Comment by Dnoob** [comment]
> > > > 还是不行，我现在用的vllm=0.14.0能部署成功和正常使用，用vllm0.16.0完全不行，参数设置都没变，0.16.0版本CUDA out of memory. 模型没加载成功。
> > > 
> > > 
> > > 请您提供以下信息，以便我们进一步调查：
> > > 
> > > 1. 您的GPU型号和显存大小（输出结果`nvidia-smi`）
> > > 2. 您使用v0.14.0 版本启动时使用的完整启动命令
> > 
> > 
> > <img alt="图像" width="1149" height="664" src="https://private-user-images.githubusercontent.com/177522180/564615718-ef35fe41-092f-48f8-b9ff-bcfbaf22be5a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzM3MzQyMTcsIm5iZiI6MTc3MzczMzkxNywicGF0aCI6Ii8xNzc1MjIxODAvNTY0NjE1NzE4LWVmMzVmZTQxLTA5MmYtNDhmOC1iOWZmLWJjZmJhZjIyYmU1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDMxN1QwNzUxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjg2YzUxODNkNGY5OGRmYTllNTM0OTg2YTFlMTQ0OGZkMGRkOGRmZjM0MWRmOTc4NTYyZjk4ODVkOTdmNDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2zqseKag82TaRnYW9aVc76XKBR-G2yNWft9phYtzTKM"> sudo docker run -d --gpus '"device=1,2"' --restart always --shm-size=32g -e NVIDIA_VISIBLE_DEVICES=1,2 -e TORCH_CUDA_ARCH_LIST="8.6+PTX" -e CUDA_MODULE_LOADING=LAZY -e NCCL_DEBUG=INFO --name qwen3-omni -v /xxxx/Qwen3-Omni-30B-A3B-Instruct:/root/models/Qwen3-Omni-30B-A3B-Instruct -p 8866:8000 vllm/vllm-omni:v0.14.0 python -m vllm.entrypoints.openai.api_server --model /root/models/Qwen3-Omni-30B-A3B-Instruct --tensor-parallel-size 2 --gpu-memory-utilization 0.92 --max-num-seqs 8 --max-model-len 65536 --limit-mm-per-prompt '{"image":10,"video":10,"audio":10}' --seed 1234 --served-model-name Qwen3-Omni-30B-A3B-Instruct --host 0.0.0.0 --port 8000 --enable-auto-tool-choice --tool-call-parser hermes
> 
> <img alt="Image" width="2000" height="1926" src="https://private-user-images.githubusercontent.com/177522180/564616657-410d3ae4-5239-4e2b-ba3d-ec13b58d974d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzM3MzcxNDQsIm5iZiI6MTc3MzczNjg0NCwicGF0aCI6Ii8xNzc1MjIxODAvNTY0NjE2NjU3LTQxMGQzYWU0LTUyMzktNGUyYi1iYTNkLWVjMTNiNThkOTc0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDMxN1QwODQwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzAyZjcwY2ZkZjU1YzZlOTlkN2E1MzA4N2EwZDI3NGE4N2I4OTQzNzEyMmQ2YjM2NzUwNWQzNDRmMDY3ZGM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MVO_5CbvSegFnckTfge64YoyAgaflG27zT43dU3kKow">

Thanks for the detailed info! Your GPUs are 2x RTX 6000 Ada (48GB each).
The issue is that v0.16.0 uses a 3-stage pipeline architecture (Thinker + Talker + Code2Wav), and the default config is designed for 2x H100-80GB. The Thinker stage is loaded entirely on a single GPU, which exceeds your 48GB VRAM.
In v0.14.0, `--tensor-parallel-size 2` splits the model evenly across both GPUs (~25GB each), so it fits. But in v0.16.0, the model is split by function (stages) rather than by size, and the Thinker stage is too large for a single 48GB card.

**Comment by watch-Ultra** [comment]
> > > > > 还是不行，我现在用的vllm=0.14.0能部署成功和正常使用，用vllm0.16.0完全不行，参数设置都没变，0.16.0版本CUDA out of memory. 模型没加载成功。
> > > > 
> > > > 
> > > > 请您提供以下信息，以便我们进一步调查：
> > > > 
> > > > 1. 您的GPU型号和显存大小（输出结果`nvidia-smi`）
> > > > 2. 您使用v0.14.0 版本启动时使用的完整启动命令
> > > 
> > > 
> > > <img alt="图像" width="1149" height="664" src="https://private-user-images.githubusercontent.com/177522180/564615718-ef35fe41-092f-48f8-b9ff-bcfbaf22be5a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzM3MzQyMTcsIm5iZiI6MTc3MzczMzkxNywicGF0aCI6Ii8xNzc1MjIxODAvNTY0NjE1NzE4LWVmMzVmZTQxLTA5MmYtNDhmOC1iOWZmLWJjZmJhZjIyYmU1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDMxN1QwNzUxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjg2YzUxODNkNGY5OGRmYTllNTM0OTg2YTFlMTQ0OGZkMGRkOGRmZjM0MWRmOTc4NTYyZjk4ODVkOTdmNDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2zqseKag82TaRnYW9aVc76XKBR-G2yNWft9phYtzTKM">sudo docker run -d --gpus '"device=1,2"' --restart always --shm-size=32g -e NVIDIA_VISIBLE_DEVICES=1,2 -e TORCH_CUDA_ARCH_LIST="8.6+PTX" -e CUDA_MODULE_LOADING=LAZY -e NCCL_DEBUG=INFO --name qwen3-omni -v /xxxx/Qwen3-Omni-30B-A3B-Instruct:/root/models/Qwen3-Omni-30B-A3B-Instruct -p 8866:8000 vllm/vllm-omni:v0.14.0 python -m vllm.entrypoints.openai.api_server --model /root/models/Qwen3-Omni-30B-A3B-Instruct --tensor-parallel-size 2 --gpu-memory-utilization 0.92 --max-num-seqs 8 --max-model-len 65536 --limit-mm-per-prompt '{"image":10,"video":10,"audio":10}' --seed 1234 --served-model-name Qwen3-Omni-30B-A3B-Instruct --host 0.0.0.0 --port 8000 --enable-auto-tool-choice --tool-call-parser hermes
> > 
> > 
> > <img alt="图像" width="2000" height="1926" src="https://private-user-images.githubusercontent.com/177522180/564616657-410d3ae4-5239-4e2b-ba3d-ec13b58d974d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzM3MzcxNDQsIm5iZiI6MTc3MzczNjg0NCwicGF0aCI6Ii8xNzc1MjIxODAvNTY0NjE2NjU3LTQxMGQzYWU0LTUyMzktNGUyYi1iYTNkLWVjMTNiNThkOTc0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDMxN1QwODQwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzAyZjcwY2ZkZjU1YzZlOTlkN2E1MzA4N2EwZDI3NGE4N2I4OTQzNzEyMmQ2YjM2NzUwNWQzNDRmMDY3ZGM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MVO_5CbvSegFnckTfge64YoyAgaflG27zT43dU3kKow">
> 
> 感谢您提供的详细信息！您的显卡是两块 RTX 6000 Ada（每块 48GB）。 问题在于 v0.16.0 版本采用了三阶段流水线架构（Thinker + Talker + Code2Wav），而默认配置是为两块 H100-80GB 显卡设计的。Thinker 阶段完全加载在一块显卡上，超过了您 48GB 的​​显存容量。 在 v0.14.0 版本中，`--tensor-parallel-size 2`模型被平均分配到两块显卡上（每块显卡约 25GB），因此可以正常运行。但在 v0.16.0 版本中，模型是按功能（阶段）而不是按大小分配的，因此 Thinker 阶段对于一块 48GB 的​​显卡来说太大了。

so,有什么解决办法吗？只能继续使用v0.14.0?

**Comment by Dnoob** [comment]
@Gaohan123 
The user's OOM issue is an architectural problem — the default stage config is verified on 2x H100-80GB, and GPUs with less VRAM (like 48GB) can't fit the Thinker stage on a single card.

Some possible approaches:
1. Support per-stage TP, so Thinker can use TP=2 across both GPUs (though this requires careful memory planning when stages share GPUs)
2. Provide alternative stage configs for different GPU sizes (e.g., 2x 48GB, 4x 24GB)
3. Add early VRAM validation with a clear error message before model loading

What's your preferred direction? Happy to work on whichever approach makes sense.

**Comment by Gaohan123** [comment]
Thanks for your patient reply. I think choice 1 makes sense. You can try to set tensor_parallel_size in stage config, just like https://github.com/vllm-project/vllm-omni/blob/main/examples/online_serving/qwen3_omni/qwen3_omni_moe_thinking.yaml

**Comment by Dnoob** [comment]
> Thanks for your patient reply. I think choice 1 makes sense. You can try to set tensor_parallel_size in stage config, just like https://github.com/vllm-project/vllm-omni/blob/main/examples/online_serving/qwen3_omni/qwen3_omni_moe_thinking.yaml

I implemented the `tensor_parallel_size: 2` approach for the Thinker stage and verified it works on 2x H20 (96GB).

However, since I don't have access to 2x 48GB GPUs to test directly, I tried simulating the 48GB constraint on H20 by halving the `gpu_memory_utilization` values (e.g., Thinker: 0.7 → 0.35, Talker: 0.2 → 0.1), so that vLLM's per-GPU memory budget matches what a real 48GB GPU would see (`0.35 × 96GB ≈ 0.7 × 48GB = 33.6GB`).

Under this simulation, the Thinker stage still failed with 0 KV cache available, suggesting that even with TP=2, the Thinker's actual memory requirement per GPU still exceeds 33.6GB.

I'm not confident this config actually works for 48GB users, what's your take on this?

**Comment by Gaohan123** [comment]
No updates over 3 weeks. I can reopen if needed
