### ISSUE TITLE
[Bug]: Cross-node --headless mode: ZMQ error in complete_diffusion_handshake under run_headless

### ISSUE THREAD

**Issue by herotai214** [vllm-project/vllm-omni#3577]
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

torch: 2.11.0+cu130
Python: 3.12.3

</details>

### Your code version

<details>
<summary>The commit id or version of vllm</summary>

```text
vLLM: v0.20.0
```
</details>
<details>
<summary>The commit id or version of vllm-omni</summary>

```
vLLM-omni:
commit https://github.com/vllm-project/vllm-omni/commit/5e263b6929ef7cb19c37800db5257f700f41871c
Author: Canlin Guo [canlinguosdu@gmail.com](mailto:canlinguosdu@gmail.com)
Date: Mon May 11 11:27:35 2026 +0800
[BugFix] Rename attention_config to diffusion_attention_config (https://github.com/vllm-project/vllm-omni/pull/3489)

```
</details>

### 🐛 Describe the bug

Following #3513 

## Cross-node: ZMQ error in complete_diffusion_handshake under run_headless

**This error never happens when running `--headless` locally**

Base on commit https://github.com/vllm-project/vllm-omni/commit/e40076e872b0ac4a458ca3abb069bfbf9806935d (12 May 12pm) and avoided the above empty stage_configs error mentioned in 3513:
When running cross-node attempt:

Let's say, running Stage 0 on node 10.128.xxx.YYY and Stage 1 Node 10.128.xxx.ZZZ
Under `run_headless` in `vllm/vllm/entrypoints/cli/serve.py`
In stage 1, after succesfully handshake with stage 0 through `"tcp://10.128.xxx.YYY:port"`, it then calls `complete_diffusion_handshake`

*It induces `zmq.error.ZMQError: Cannot assign requested address (addr='tcp://10.128.xxx.YYY:41257')`*

<details><summary>Detailed Error log: </summary>

```
INFO 05-13 06:14:57 [serve.py:606] hero: stage_configs after force parse in: [namespace(stage_id=0, stage_type='llm', engine_args={'model_arch': 'HunyuanImage3ForCausalMM', 'engine_output_type': 'latent', 'trust_remote_code': True, 'tensor_parallel_size': 4, 'gpu_memory_utilization': 0.95, 'max_num_seqs': 1, 'max_num_batched_tokens': 32768, 'enforce_eager': True, 'is_comprehension': False, 'final_output': True, 'final_output_type': 'text', 'hf_overrides': {'rope_parameters': {'mrope_section': [0, 32, 32], 'rope_type': 'default'}}, 'omni_kv_config': {'need_send_cache': True}, 'async_chunk': False, 'async_scheduling': True, 'model_stage': 'AR', 'worker_type': 'ar', 'scheduler_cls': 'vllm_omni.core.sched.omni_ar_scheduler.OmniARAsyncScheduler', 'subparser': 'serve', 'model_tag': '/home/dyvm6xra/dyvm6xrauser68/hero/models/HunyuanImage-3.0-Instruct', 'headless': False, 'grpc': False, 'chat_template_content_format': 'auto', 'trust_request_chat_template': False, 'response_role': 'assistant', 'return_tokens_as_token_ids': False, 'enable_auto_tool_choice': False, 'exclude_tools_when_tool_choice_none': False, 'tool_parser_plugin': '', 'enable_prompt_tokens_details': False, 'enable_server_load_tracking': False, 'enable_force_include_usage': False, 'enable_tokenizer_info_endpoint': False, 'enable_log_outputs': False, 'enable_log_deltas': True, 'log_error_stack': False, 'port': 9878, 'uvicorn_log_level': 'info', 'disable_uvicorn_access_log': False, 'allow_credentials': False, 'allowed_origins': ['*'], 'allowed_methods': ['*'], 'allowed_headers': ['*'], 'enable_ssl_refresh': False, 'ssl_cert_reqs': 0, 'middleware': [], 'enable_request_id_headers': False, 'disable_fastapi_docs': False, 'h11_max_incomplete_event_size': 4194304, 'h11_max_header_count': 256, 'enable_offline_docs': False, 'enable_flash_late_interaction': True, 'allowed_local_media_path': '', 'worker_extension_cls': '', 'enable_log_requests': False, 'omni': True, 'replica_id': 0, 'omni_master_address': '10.128.xxx.YYY', 'omni_master_port': 34567, 'diffusers_load_kwargs': {}, 'diffusers_call_kwargs': {}, 'ulysses_mode': 'strict', 'use_hsdp': False, 'hsdp_shard_size': -1, 'hsdp_replicate_size': 1, 'cache_backend': 'none', 'enable_cache_dit_summary': False, 'step_execution': False, 'vae_use_slicing': False, 'vae_use_tiling': False, 'enable_multithread_weight_load': True, 'num_weight_load_threads': 4, 'enable_cpu_offload': False, 'enable_layerwise_offload': False, 'cfg_parallel_size': 1, 'vae_patch_parallel_size': 1, 'enable_diffusion_pipeline_profiler': False}, runtime={'process': True, 'devices': '0,1,2,3', 'num_replicas': 1, 'requires_multimodal_data': True}, engine_input_source=[], final_output=False, final_output_type=None, is_comprehension=False, default_sampling_params={'temperature': 0.0, 'top_p': 1, 'top_k': -1, 'max_tokens': 8192, 'detokenize': True, 'skip_special_tokens': False}, output_connectors={'to_stage_1': 'shared_memory_connector'}), namespace(stage_id=1, stage_type='diffusion', engine_args={'model_arch': 'HunyuanImage3ForCausalMM', 'trust_remote_code': True, 'max_num_seqs': 1, 'enforce_eager': True, 'distributed_executor_backend': 'mp', 'omni_kv_config': {'need_recv_cache': True}, 'parallel_config': {'tensor_parallel_size': 4, 'enable_expert_parallel': True}, 'async_chunk': False, 'model_stage': 'dit', 'subparser': 'serve', 'model_tag': '/home/dyvm6xra/dyvm6xrauser68/hero/models/HunyuanImage-3.0-Instruct', 'headless': False, 'grpc': False, 'chat_template_content_format': 'auto', 'trust_request_chat_template': False, 'response_role': 'assistant', 'return_tokens_as_token_ids': False, 'enable_auto_tool_choice': False, 'exclude_tools_when_tool_choice_none': False, 'tool_parser_plugin': '', 'enable_prompt_tokens_details': False, 'enable_server_load_tracking': False, 'enable_force_include_usage': False, 'enable_tokenizer_info_endpoint': False, 'enable_log_outputs': False, 'enable_log_deltas': True, 'log_error_stack': False, 'port': 9878, 'uvicorn_log_level': 'info', 'disable_uvicorn_access_log': False, 'allow_credentials': False, 'allowed_origins': ['*'], 'allowed_methods': ['*'], 'allowed_headers': ['*'], 'enable_ssl_refresh': False, 'ssl_cert_reqs': 0, 'middleware': [], 'enable_request_id_headers': False, 'disable_fastapi_docs': False, 'h11_max_incomplete_event_size': 4194304, 'h11_max_header_count': 256, 'enable_offline_docs': False, 'enable_flash_late_interaction': True, 'allowed_local_media_path': '', 'worker_extension_cls': '', 'enable_log_requests': False, 'omni': True, 'replica_id': 0, 'omni_master_address': '10.128.xxx.YYY', 'omni_master_port': 34567, 'diffusers_load_kwargs': {}, 'diffusers_call_kwargs': {}, 'ulysses_mode': 'strict', 'use_hsdp': False, 'hsdp_shard_size': -1, 'hsdp_replicate_size': 1, 'cache_backend': 'none', 'enable_cache_dit_summary': False, 'step_execution': False, 'vae_use_slicing': False, 'vae_use_tiling': False, 'enable_multithread_weight_load': True, 'num_weight_load_threads': 4, 'enable_cpu_offload': False, 'enable_layerwise_offload': False, 'cfg_parallel_size': 1, 'vae_patch_parallel_size': 1, 'enable_diffusion_pipeline_profiler': False}, runtime={'process': True, 'devices': '0,1,2,3', 'num_replicas': 1, 'requires_multimodal_data': True}, engine_input_source=[0], final_output=True, final_output_type='image', is_comprehension=False, custom_process_input_func='vllm_omni.model_executor.stage_input_processors.hunyuan_image3.ar2diffusion', default_sampling_params={'num_inference_steps': 50, 'guidance_scale': 0}, input_connectors={'from_stage_0': 'shared_memory_connector'})]
INFO 05-13 06:14:57 [initialization.py:351] Loaded OmniTransferConfig with 1 connector configurations
INFO 05-13 06:14:57 [serve.py:630] [Headless] Launching diffusion stage 1 replica 0 via OmniMasterServer at 10.128.xxx.YYY:34567
INFO 05-13 06:15:03 [stage_engine_startup.py:409] Stage 1 registered; handshake_address=tcp://10.128.xxx.YYY:41257
INFO 05-13 06:15:03 [serve.py:661] [Headless] Shutting down stage 1 replica 0.
Traceback (most recent call last):
  File "/home/dyvm6xra/dyvm6xrauser68/hero/env_15/bin/vllm", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/dyvm6xra/dyvm6xrauser68/hero/env_15/lib/python3.12/site-packages/vllm/entrypoints/cli/main.py", line 52, in main
    omni_main()
  File "/home/dyvm6xra/dyvm6xrauser68/hero/vllm-omni/vllm_omni/entrypoints/cli/main.py", line 65, in main
    args.dispatch_function(args)
  File "/home/dyvm6xra/dyvm6xrauser68/hero/vllm-omni/vllm_omni/entrypoints/cli/serve.py", line 98, in cmd
    run_headless(args)
  File "/home/dyvm6xra/dyvm6xrauser68/hero/vllm-omni/vllm_omni/entrypoints/cli/serve.py", line 655, in run_headless
    complete_diffusion_handshake(proc, handshake_address, args.stage_init_timeout)
  File "/home/dyvm6xra/dyvm6xrauser68/hero/vllm-omni/vllm_omni/diffusion/stage_diffusion_proc.py", line 597, in complete_diffusion_handshake
    _perform_diffusion_handshake(proc, handshake_address, handshake_timeout)
  File "/home/dyvm6xra/dyvm6xrauser68/hero/vllm-omni/vllm_omni/diffusion/stage_diffusion_proc.py", line 609, in _perform_diffusion_handshake
    with zmq_socket_ctx(handshake_address, zmq.ROUTER, bind=True) as handshake_socket:
  File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/dyvm6xra/dyvm6xrauser68/hero/env_15/lib/python3.12/site-packages/vllm/utils/network_utils.py", line 358, in zmq_socket_ctx
    yield make_zmq_socket(
          ^^^^^^^^^^^^^^^^
  File "/home/dyvm6xra/dyvm6xrauser68/hero/env_15/lib/python3.12/site-packages/vllm/utils/network_utils.py", line 338, in make_zmq_socket
    socket.bind(path)
  File "/home/dyvm6xra/dyvm6xrauser68/hero/env_15/lib/python3.12/site-packages/zmq/sugar/socket.py", line 320, in bind
    super().bind(addr)
  File "zmq/backend/cython/_zmq.py", line 1009, in zmq.backend.cython._zmq.Socket.bind
  File "zmq/backend/cython/_zmq.py", line 190, in zmq.backend.cython._zmq._check_rc
zmq.error.ZMQError: Cannot assign requested address (addr='tcp://10.128.xxx.YYY:41257')

```

```
...
        try:
            handshake_address, request_address, response_address = register_stage_with_omni_master(
                omni_master_address=omni_master_address,
                omni_master_port=omni_master_port,
                omni_stage_id=stage_id,
                omni_stage_config=stage_cfg,
                return_addresses=True,
                replica_id=replica_id,
            )
            proc, _, _, _ = spawn_diffusion_proc(
                model,
                od_config,
                handshake_address=handshake_address,
                request_address=request_address,
                response_address=response_address,
            )
            complete_diffusion_handshake(proc, handshake_address, args.stage_init_timeout)   # <---- error occurs here

...

```
</details>

## Failed attempt to fix: change sock.bind() to sock.connect()

In `_perform_diffusion_handshake` under `vllm-omni/vllm_omni/diffusion/stage_diffusion_proc.py`
`with zmq_socket_ctx(handshake_address, zmq.ROUTER, bind=True) as handshake_socket:`

The NPU team experienced the same issue. An attempt to try fixing the issue by setting **bind=False**, such that it goes to `socket.connect(path)` instead.

**It didn't work.**
- sock.bind(path): Error message appears instantly
- **sock.connect(path): Stage 1 continue setting and "finish setup"; but 300s later it throws a handshake timeout error **

In `make_zmq_socket` under `vllm/vllm/utils/network_utils.py`:

```
...
    if bind:
        socket.bind(path)
    else:
        socket.connect(path)

    return socket
```

The relevant sock.bind(path) error log previously:
```
line 358, in zmq_socket_ctx
    yield make_zmq_socket(
          ^^^^^^^^^^^^^^^^
  File "/home/dyvm6xra/dyvm6xrauser68/hero/env_15/lib/python3.12/site-packages/vllm/utils/network_utils.py", line 338, in make_zmq_socket
    socket.bind(path)
  File "/home/dyvm6xra/dyvm6xrauser68/hero/env_15/lib/python3.12/site-packages/zmq/sugar/socket.py", line 320, in bind
    super().bind(addr)
  File "zmq/backend/cython/_zmq.py", line 1009, in zmq.backend.cython._zmq.Socket.bind
  File "zmq/backend/cython/_zmq.py", line 190, in zmq.backend.cython._zmq._check_rc
zmq.error.ZMQError: Cannot assign requested address (addr='tcp://10.128.xxx.YYY:41257')
```

The sock.connect(path) log which didnt throw error at first but gives timeout error later:
```
...
!!!!!!!!!!!!!!!!###### it didnt fail right after handshake ############!!!!!!!!!!!!!!!!

INFO 05-13 10:07:35 [serve.py:701] hero: stage_configs after force parse in: [namespace(stage_id=0, stage_type='llm', engine_args={'model_arch': 'HunyuanImage3ForCausalMM', 'engine_output_type': 'latent', 'trust_remote_code': True, 'tensor_parallel_size': 4, 'gpu_memory_utilization': 0.95, 'max_num_seqs': 1, 'max_num_batched_tokens': 32768, 'enforce_eager': True, 'is_comprehension': False, 'final_output': True, 'final_output_type': 'text', 'hf_overrides': {'rope_parameters': {'mrope_section': [0, 32, 32], 'rope_type': 'default'}}, 'omni_kv_config': {'need_send_cache': True}, 'async_chunk': False, 'async_scheduling': True, 'model_stage': 'AR', 'worker_type': 'ar', 'scheduler_cls': 'vllm_omni.core.sched.omni_ar_scheduler.OmniARAsyncScheduler', 'subparser': 'serve', 'model_tag': '/home/dyvm6xra/dyvm6xrauser68/hero/models/HunyuanImage-3.0-Instruct', 'headless': False, 'grpc': False, 'chat_template_content_format': 'auto', 'trust_request_chat_template': False, 'response_role': 'assistant', 'return_tokens_as_token_ids': False, 'enable_auto_tool_choice': False, 'exclude_tools_when_tool_choice_none': False, 'tool_parser_plugin': '', 'enable_prompt_tokens_details': False, 'enable_server_load_tracking': False, 'enable_force_include_usage': False, 'enable_tokenizer_info_endpoint': False, 'enable_log_outputs': False, 'enable_log_deltas': True, 'log_error_stack': False, 'host': '127.0.0.1', 'port': 9878, 'uvicorn_log_level': 'info', 'disable_uvicorn_access_log': False, 'allow_credentials': False, 'allowed_origins': ['*'], 'allowed_methods': ['*'], 'allowed_headers': ['*'], 'enable_ssl_refresh': False, 'ssl_cert_reqs': 0, 'middleware': [], 'enable_request_id_headers': False, 'disable_fastapi_docs': False, 'h11_max_incomplete_event_size': 4194304, 'h11_max_header_count': 256, 'enable_offline_docs': False, 'enable_flash_late_interaction': True, 'allowed_local_media_path': '', 'worker_extension_cls': '', 'enable_log_requests': False, 'omni': True, 'replica_id': 0, 'omni_master_address': '10.248.12.160', 'omni_master_port': 34577, 'omni_dp_size_local': 1, 'omni_lb_policy': 'random', 'omni_heartbeat_timeout': 30.0, 'diffusers_load_kwargs': {}, 'diffusers_call_kwargs': {}, 'ulysses_mode': 'strict', 'use_hsdp': False, 'hsdp_shard_size': -1, 'hsdp_replicate_size': 1, 'cache_backend': 'none', 'enable_cache_dit_summary': False, 'step_execution': False, 'vae_use_slicing': False, 'vae_use_tiling': False, 'enable_multithread_weight_load': True, 'num_weight_load_threads': 4, 'enable_cpu_offload': False, 'enable_layerwise_offload': False, 'cfg_parallel_size': 1, 'vae_patch_parallel_size': 1, 'enable_diffusion_pipeline_profiler': False}, runtime={'process': True, 'devices': '0,1,2,3', 'num_replicas': 1, 'requires_multimodal_data': True}, engine_input_source=[], final_output=False, final_output_type=None, is_comprehension=False, default_sampling_params={'temperature': 0.0, 'top_p': 1, 'top_k': -1, 'max_tokens': 8192, 'detokenize': True, 'skip_special_tokens': False}, output_connectors={'to_stage_1': 'shared_memory_connector'}), namespace(stage_id=1, stage_type='diffusion', engine_args={'model_arch': 'HunyuanImage3ForCausalMM', 'trust_remote_code': True, 'max_num_seqs': 1, 'enforce_eager': True, 'distributed_executor_backend': 'mp', 'omni_kv_config': {'need_recv_cache': True}, 'parallel_config': {'tensor_parallel_size': 4, 'enable_expert_parallel': True}, 'async_chunk': False, 'model_stage': 'dit', 'subparser': 'serve', 'model_tag': '/home/dyvm6xra/dyvm6xrauser68/hero/models/HunyuanImage-3.0-Instruct', 'headless': False, 'grpc': False, 'chat_template_content_format': 'auto', 'trust_request_chat_template': False, 'response_role': 'assistant', 'return_tokens_as_token_ids': False, 'enable_auto_tool_choice': False, 'exclude_tools_when_tool_choice_none': False, 'tool_parser_plugin': '', 'enable_prompt_tokens_details': False, 'enable_server_load_tracking': False, 'enable_force_include_usage': False, 'enable_tokenizer_info_endpoint': False, 'enable_log_outputs': False, 'enable_log_deltas': True, 'log_error_stack': False, 'host': '127.0.0.1', 'port': 9878, 'uvicorn_log_level': 'info', 'disable_uvicorn_access_log': False, 'allow_credentials': False, 'allowed_origins': ['*'], 'allowed_methods': ['*'], 'allowed_headers': ['*'], 'enable_ssl_refresh': False, 'ssl_cert_reqs': 0, 'middleware': [], 'enable_request_id_headers': False, 'disable_fastapi_docs': False, 'h11_max_incomplete_event_size': 4194304, 'h11_max_header_count': 256, 'enable_offline_docs': False, 'enable_flash_late_interaction': True, 'allowed_local_media_path': '', 'worker_extension_cls': '', 'enable_log_requests': False, 'omni': True, 'replica_id': 0, 'omni_master_address': '10.248.12.160', 'omni_master_port': 34577, 'omni_dp_size_local': 1, 'omni_lb_policy': 'random', 'omni_heartbeat_timeout': 30.0, 'diffusers_load_kwargs': {}, 'diffusers_call_kwargs': {}, 'ulysses_mode': 'strict', 'use_hsdp': False, 'hsdp_shard_size': -1, 'hsdp_replicate_size': 1, 'cache_backend': 'none', 'enable_cache_dit_summary': False, 'step_execution': False, 'vae_use_slicing': False, 'vae_use_tiling': False, 'enable_multithread_weight_load': True, 'num_weight_load_threads': 4, 'enable_cpu_offload': False, 'enable_layerwise_offload': False, 'cfg_parallel_size': 1, 'vae_patch_parallel_size': 1, 'enable_diffusion_pipeline_profiler': False}, runtime={'process': True, 'devices': '0,1,2,3', 'num_replicas': 1, 'requires_multimodal_data': True}, engine_input_source=[0], final_output=True, final_output_type='image', is_comprehension=False, custom_process_input_func='vllm_omni.model_executor.stage_input_processors.hunyuan_image3.ar2diffusion', default_sampling_params={'num_inference_steps': 50, 'guidance_scale': 0}, input_connectors={'from_stage_0': 'shared_memory_connector'})]
DEBUG 05-13 10:07:35 [__init__.py:31] No plugins for group vllm_omni.general_plugins found.
INFO 05-13 10:07:35 [initialization.py:351] Loaded OmniTransferConfig with 1 connector configurations
INFO 05-13 10:07:35 [serve.py:752] [Headless] Launching 1 diffusion replica(s) for stage 1 via OmniMasterServer at 10.248.12.160:34577
INFO 05-13 10:07:50 [stage_engine_startup.py:579] Stage 1 replica 0 registered; handshake_address=tcp://10.248.12.160:51817
[37mDEBUG[0m [90m05-13 10:07:53[0m [90m[plugins/__init__.py:36][0m No plugins for group vllm.platform_plugins found.
[37mDEBUG[0m [90m05-13 10:07:53[0m [90m[platforms/__init__.py:37][0m Checking if TPU platform is available.
[37mDEBUG[0m [90m05-13 10:07:53[0m [90m[platforms/__init__.py:56][0m TPU platform is not available because: No module named 'libtpu'
[37mDEBUG[0m [90m05-13 10:07:53[0m [90m[platforms/__init__.py:62][0m Checking if CUDA platform is available.
[37mDEBUG[0m [90m05-13 10:07:53[0m [90m[platforms/__init__.py:85][0m Confirmed CUDA platform is available.
[37mDEBUG[0m [90m05-13 10:07:53[0m [90m[platforms/__init__.py:113][0m Checking if ROCm platform is available.
[37mDEBUG

....


!!!!!!!!!!!!!!!############ successful model load ############!!!!!!!!!!!!!!!!

[37mDEBUG[0m [90m05-13 10:08:48[0m [90m[model_executor/models/utils.py:227][0m Loaded weight vision_model.post_layernorm.weight with shape torch.Size([1152])
[32mINFO[0m [90m05-13 10:08:49[0m [90m[diffusion_worker.py:273][0m Worker 3: Process-scoped GPU memory after model loading: 0.00 GiB.
[32mINFO[0m [90m05-13 10:08:49[0m [90m[manager.py:96][0m Initializing DiffusionLoRAManager: device=cuda:3, dtype=torch.bfloat16, max_cached_adapters=1, static_lora_path=None
[32mINFO[0m [90m05-13 10:08:49[0m [90m[diffusion_worker.py:171][0m Worker 3: Initialization complete.
[32mINFO[0m [90m05-13 10:08:49[0m [90m[diffusion_worker.py:780][0m Worker 3: Scheduler loop started.
[32mINFO[0m [90m05-13 10:08:49[0m [90m[diffusion_worker.py:690][0m Worker 3 ready to receive requests via shared memory
[32mINFO[0m [90m05-13 10:08:49[0m [90m[diffusion_model_runner.py:144][0m Model loading took 42.3181 GiB and 14.033798 seconds
[32mINFO[0m [90m05-13 10:08:49[0m [90m[diffusion_model_runner.py:149][0m Model runner: Model loaded successfully.
[32mINFO[0m [90m05-13 10:08:49[0m [90m[diffusion_model_runner.py:190][0m Model runner: Initialization complete.
[37mDEBUG[0m [90m05-13 10:08:49[0m [90m[distributed/device_communicators/shm_broadcast.py:196][0m Poller timed out
[32mINFO[0m [90m05-13 10:08:49[0m [90m[diffusion_worker.py:273][0m Worker 2: Process-scoped GPU memory after model loading: 0.00 GiB.
[32mINFO[0m [90m05-13 10:08:49[0m [90m[manager.py:96][0m Initializing DiffusionLoRAManager: device=cuda:2, dtype=torch.bfloat16, max_cached_adapters=1, static_lora_path=None
[32mINFO[0m [90m05-13 10:08:49[0m [90m[diffusion_worker.py:171][0m Worker 2: Initialization complete.
[32mINFO[0m [90m05-13 10:08:49[0m [90m[diffusion_worker.py:780][0m Worker 2: Scheduler loop started.
[32mINFO[0m [90m05-13 10:08:49[0m [90m[diffusion_worker.py:690][0m Worker 2 ready to receive requests via shared memory
[37mDEBUG[0m [90m05-13 10:08:49[0m [90m[multiproc_executor.py:197][0m All workers are ready
[37mDEBUG[0m [90m05-13 10:08:49[0m [90m[distributed/device_communicators/shm_broadcast.py:467][0m Connecting to ipc:///tmp/2ad02b2d-111d-4f8e-a111-c426436cf678
[32mINFO[0m [90m05-13 10:08:49[0m [90m[diffusion_engine.py:699][0m dummy run to warm up the model
[37mDEBUG[0m [90m05-13 10:08:49[0m [90m[distributed/device_communicators/shm_broadcast.py:196][0m Poller timed out
[37mDEBUG[0m [90m05-13 10:08:49[0m [90m[base_scheduler.py:76][0m RequestScheduler add_request: dummy_req_id (waiting=1)


!!!!!!!!!!!!!!!!############ if wait long enough, timeout error will come out ############!!!!!!!!!!!!!!!!
[37mDEBUG[0m [90m05-13 10:12:45[0m [90m[distributed/device_communicators/shm_broadcast.py:196][0m Poller timed out
[37mDEBUG[0m [90m05-13 10:12:50[0m [90m[distributed/device_communicators/shm_broadcast.py:196][0m Poller timed out
[37mDEBUG[0m [90m05-13 10:12:50[0m [90m[stage_diffusion_proc.py:596][0m StageDiffusionProc exiting.
[31mERROR[0m [90m05-13 10:12:50[0m [90m[multiproc_executor.py:236][0m Diffusion worker(s) died unexpectedly: ['DiffusionWorker-3(exitcode=None)']
[33mWARNING[0m [90m05-13 10:12:51[0m [90m[multiproc_executor.py:65][0m Terminating diffusion worker DiffusionWorker-0 after timeout
[33mWARNING[0m [90m05-13 10:12:51[0m [90m[multiproc_executor.py:65][0m Terminating diffusion worker DiffusionWorker-2 after timeout
INFO 05-13 10:12:53 [serve.py:851] [Headless] Shutting down 0 diffusion replica(s) for stage 1.
Traceback (most recent call last):
  File "/home/dyvm6xra/dyvm6xrauser68/hero/env_15/bin/vllm", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/dyvm6xra/dyvm6xrauser68/hero/env_15/lib/python3.12/site-packages/vllm/entrypoints/cli/main.py", line 52, in main
    omni_main()
  File "/home/dyvm6xra/dyvm6xrauser68/hero/vllm-omni/vllm_omni/entrypoints/cli/main.py", line 65, in main
    args.dispatch_function(args)
  File "/home/dyvm6xra/dyvm6xrauser68/hero/vllm-omni/vllm_omni/entrypoints/cli/serve.py", line 100, in cmd
    run_headless(args)
  File "/home/dyvm6xra/dyvm6xrauser68/hero/vllm-omni/vllm_omni/entrypoints/cli/serve.py", line 823, in run_headless
    complete_diffusion_handshake(proc, response.handshake_address, args.stage_init_timeout)
  File "/home/dyvm6xra/dyvm6xrauser68/hero/vllm-omni/vllm_omni/diffusion/stage_diffusion_proc.py", line 670, in complete_diffusion_handshake
    _perform_diffusion_handshake(proc, handshake_address, handshake_timeout)
  File "/home/dyvm6xra/dyvm6xrauser68/hero/vllm-omni/vllm_omni/diffusion/stage_diffusion_proc.py", line 691, in _perform_diffusion_handshake
    raise TimeoutError(
TimeoutError: Timed out waiting for READY from StageDiffusionProc after 300s. This typically indicates model loading or warmup is taking too long. Consider increasing `stage_init_timeout` for large models.
/usr/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 4 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/usr/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '


```

<details><summary>Cross-node starting script reference: </summary>

```
# Run Stage 0 on node 10.128.xxx.YYY
CUDA_VISIBLE_DEVICES=0,1,2,3 \
vllm serve "/mnt/nvme3n1/models/HunyuanImage-3.0-Instruct/" \
  --omni \
  --stage-id 0 \
  --stage-configs-path /workspace/hero/hero_omni_alt/vllm-omni/vllm_omni/deploy/hunyuan_image3.yaml \
  --omni-master-address 10.128.xxx.YYY \
  --omni-master-port 37565 \
  --port 9878 > ${LOG_PATH}/online_hunyuan0_e40076_$(date +"%Y%m%d_%H%M%S").log 2>&1 &

# Run Stage 1 Node 10.128.xxx.ZZZ
CUDA_VISIBLE_DEVICES=0,1,2,3 \
vllm serve "/mnt/nvme3n1/models/HunyuanImage-3.0-Instruct/" \
  --omni \
  --stage-id 1 \
  --headless \
  --stage-configs-path /workspace/hero/hero_omni_alt/vllm-omni/vllm_omni/deploy/hunyuan_image3.yaml \
  --omni-master-address 10.128.xxx.YYY \         # <--- write the IP of the stage 0 node here
  --omni-master-port 37565 > ${LOG_PATH}/online_hunyuan1_e40076_$(date +"%Y%m%d_%H%M%S").log 2>&1 &

```

</details>

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://vllm-omni.readthedocs.io), which can answer lots of frequently asked questions.

**Comment by herotai214** [comment]
cc @Gaohan123 @wuhang2014 @chickeyton @jiangmengyu18

**Comment by herotai214** [comment]
BTW this bug also appears for the code in [WIP] Integrate OmniCoordinator into stage engine pipeline
#3569 too
(**It's believed that this is a general bug for all models that need to run --headless in cross-node.**.
Right now only tested with `HunyuanImage-3.0-Instruct` cross-node, will provide evidence with other models in cross-node later if needed. )

**Comment by chickeyton** [comment]
it seems like the wanted port is occupied by another process already, I will verify later

**Comment by herotai214** [comment]
> BTW this bug also appears for the code in [WIP] Integrate OmniCoordinator into stage engine pipeline [#3569](https://github.com/vllm-project/vllm-omni/pull/3569) too (**It's believed that this is a general bug for all models that need to run --headless in cross-node.**. Right now only tested with `HunyuanImage-3.0-Instruct` cross-node, will provide evidence with other models in cross-node later if needed. )

Update:
Confirmed that  `BAGEL-7B-MoT` also has the exact same ZMQ error behavior under the PR branch;

I verified that running `--headless` with `BAGEL-7B-MoT` local works fine and perfectly output.

**Comment by Gaohan123** [comment]
@wuhang2014 PTAL. Thanks

**Comment by chickeyton** [comment]
It is due to `run_headless()` use master address as the binding address for the replica's ZMQ sockets, PR#3569 fixed by adding `--omni-replica-address`, if it is omitted then `run_headless()` will auto detect from the network interface
