### ISSUE TITLE
[Bug]: OmniVoice crashes in ROCm

### ISSUE THREAD

**Issue by davispuh** [vllm-project/vllm-omni#3888]
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>
```text
==============================
        System Info
==============================
OS                           : Arch Linux (x86_64)
GCC version                  : (GCC) 16.1.1 20260430
Clang version                : 22.1.5
CMake version                : version 4.3.3
Libc version                 : glibc-2.43

==============================
       PyTorch Info
==============================
PyTorch version              : 2.12.0
Is debug build               : False
CUDA used to build PyTorch   : N/A
ROCM used to build PyTorch   : 7.2.53211

==============================
      Python Environment
==============================
Python version               : 3.14.5 (main, May 10 2026, 18:26:20) [GCC 16.1.1 20260430] (64-bit runtime)
Python platform              : Linux-7.0.10-arch1-1-x86_64-with-glibc2.43

==============================
       CUDA / GPU Info
==============================
Is CUDA available            : True
CUDA runtime version         : Could not collect
CUDA_MODULE_LOADING set to   : 
GPU models and configuration : AMD Radeon RX 7900 XTX (gfx1100)
Nvidia driver version        : Could not collect
cuDNN version                : Could not collect
HIP runtime version          : 7.2.53211
MIOpen runtime version       : 3.5.1
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                            x86_64
CPU op-mode(s):                          32-bit, 64-bit
Address sizes:                           43 bits physical, 48 bits virtual
Byte Order:                              Little Endian
CPU(s):                                  24
On-line CPU(s) list:                     0-23
Vendor ID:                               AuthenticAMD
Model name:                              AMD Ryzen Threadripper 1920X 12-Core Processor
CPU family:                              23
Model:                                   1
Thread(s) per core:                      2
Core(s) per socket:                      12
Socket(s):                               1
Stepping:                                1
Microcode version:                       0x8001137
Frequency boost:                         enabled
CPU(s) scaling MHz:                      94%
CPU max MHz:                             3500,0000
CPU min MHz:                             2200,0000
BogoMIPS:                                6985,98
Flags:                                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca sev
Virtualization:                          AMD-V
L1d cache:                               384 KiB (12 instances)
L1i cache:                               768 KiB (12 instances)
L2 cache:                                6 MiB (12 instances)
L3 cache:                                32 MiB (4 instances)
NUMA node(s):                            1
NUMA node0 CPU(s):                       0-23
Vulnerability Gather data sampling:      Not affected
Vulnerability Ghostwrite:                Not affected
Vulnerability Indirect target selection: Not affected
Vulnerability Itlb multihit:             Not affected
Vulnerability L1tf:                      Not affected
Vulnerability Mds:                       Not affected
Vulnerability Meltdown:                  Not affected
Vulnerability Mmio stale data:           Not affected
Vulnerability Old microcode:             Not affected
Vulnerability Reg file data sampling:    Not affected
Vulnerability Retbleed:                  Mitigation; untrained return thunk; SMT vulnerable
Vulnerability Spec rstack overflow:      Mitigation; Safe RET
Vulnerability Spec store bypass:         Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:                Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:                Mitigation; Retpolines; IBPB conditional; STIBP disabled; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                     Not affected
Vulnerability Tsa:                       Not affected
Vulnerability Tsx async abort:           Not affected
Vulnerability Vmscape:                   Mitigation; IBPB before exit to userspace

==============================
Versions of relevant libraries
==============================
[pip3] flake8==7.3.0
[pip3] mypy_extensions==1.1.0
[pip3] numpy==2.4.6
[pip3] onnxruntime==1.24.4
[pip3] optree==0.19.0
[pip3] pyzmq==27.1.0
[pip3] torch==2.12.0
[pip3] torchaudio==2.11.0+dadc871
[pip3] torchvision==0.27.0
[pip3] transformers==5.7.0
[pip3] triton==3.5.1+git0add6826
[pip3] x-transformers==2.2.12
[conda] Could not collect

==============================
         vLLM Info
==============================
ROCM Version                 : 7.2.53211-9999
vLLM Version                 : 0.21.1.dev0+gad7125a43.d20260523 (git sha: ad7125a43, date: 20260523)
vLLM-Omni Version            : 0.20.1.dev171+ge7644daa7.d20260522.rocm (git sha: e7644daa7, date: ocm)
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled
GPU Topology:
  ============================ ROCm System Management Interface ============================
================================ Weight between two GPUs =================================
       GPU0         
GPU0   0            

================================= Hops between two GPUs ==================================
       GPU0         
GPU0   0            

=============================== Link Type between two GPUs ===============================
       GPU0         
GPU0   0            

======================================= Numa Nodes =======================================
GPU[0]          : (Topology) Numa Node: 0
GPU[0]          : (Topology) Numa Affinity: -1
================================== End of ROCm SMI Log ===================================

==============================
     Environment Variables
==============================
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
```

</details>

### Your code version

<details>
<summary>The commit id or version of vllm</summary>

```text
0.21.1.dev0+gad7125a43.d20260523
```
</details>
<details>
<summary>The commit id or version of vllm-omni</summary>

```text
e7644daa7f45610665f33d85682ba24014186698
```
</details>

### 🐛 Describe the bug

When running `examples/offline_inference/text_to_speech/omnivoice/end2end.py` with ROCm then it crashes with:
```
/usr/include/c++/16.1.1/bits/stl_vector.h:1253: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = rocr::core::AqlPacket; _Alloc = std::allocator<rocr::core::AqlPacket>; reference = rocr::core::AqlPacket&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
```

I narrowed it down to loop in `forward()` in `model_executor/models/omnivoice/omnivoice_generator.py`
If I add this (`torch.cuda.synchronize()` at end of loop):
```diff
diff --git a/vllm_omni/model_executor/models/omnivoice/omnivoice_generator.py b/vllm_omni/model_executor/models/omnivoice/omnivoice_generator.py
index 0de2a1f6..658ab763 100644
--- a/vllm_omni/model_executor/models/omnivoice/omnivoice_generator.py
+++ b/vllm_omni/model_executor/models/omnivoice/omnivoice_generator.py
@@ -926,6 +926,8 @@ class OmniVoiceGenerator(nn.Module):
                 input_ids[i, :, c_len - t_len : c_len] = sample_tokens.squeeze(0)
                 input_ids[B + i, :, :t_len] = sample_tokens.squeeze(0)
 
+            torch.cuda.synchronize()
+
         return tokens
 
     def load_weights(self, model_dir: str, device: torch.device) -> None:
```
Then it doesn't crash and works correctly. It also doesn't crash if I use `HIP_LAUNCH_BLOCKING=1`.

I'm guessing it's probably ROCm bug but putting it here for reference and to save time for others.
Backtrace looks like this:
```text
#2  0x00007ffff743e7d0 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7425681 in __GI_abort () at abort.c:77
#4  0x00007ffff5a9d5b9 in std::__glibcxx_assert_fail (file=file@entry=0x7fff003697a8 "/usr/include/c++/16.1.1/bits/stl_vector.h", line=line@entry=1253, 
    function=function@entry=0x7fff00372248 "std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = rocr::core::AqlPacket; _Alloc = std::allocator<rocr::core::AqlPacket>; reference = rocr::core::AqlPacket"..., condition=condition@entry=0x7fff00365014 "__n < this->size()") at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/assert_fail.cc:41
#5  0x00007fff0021ac3e in std::vector<rocr::core::AqlPacket, std::allocator<rocr::core::AqlPacket> >::operator[] (this=<optimized out>, __n=<optimized out>) at /usr/include/c++/16.1.1/bits/stl_vector.h:1251
#6  std::vector<rocr::core::AqlPacket, std::allocator<rocr::core::AqlPacket> >::operator[] (this=0x5555747b5ac8, __n=<optimized out>) at /usr/include/c++/16.1.1/bits/stl_vector.h:1251
#7  rocr::core::InterceptQueue::StoreRelaxed (this=<optimized out>, value=<optimized out>)
    at /usr/src/debug/hsa-rocr/rocm-systems-rocm-7.2.3/projects/rocr-runtime/runtime/hsa-runtime/core/runtime/intercept_queue.cpp:410
#8  0x00007fff00264052 in rocr::HSA::hsa_signal_store_screlease (hsa_signal=..., value=38933) at /usr/src/debug/hsa-rocr/rocm-systems-rocm-7.2.3/projects/rocr-runtime/runtime/hsa-runtime/core/runtime/hsa.cpp:1234
#9  0x00007fff61463ea4 in amd::roc::Hsa::signal_store_screlease (signal=..., value=<optimized out>) at /usr/src/debug/hip-runtime/rocm-systems-rocm-7.2.3/projects/clr/rocclr/device/rocm/rocrctx.hpp:236
#10 amd::roc::VirtualGPU::dispatchGenericAqlPacket<hsa_kernel_dispatch_packet_s> (this=0x555574274b00, packet=0x7fffffff9e10, header=<optimized out>, rest=<optimized out>, blocking=<optimized out>, 
    attach_signal=<optimized out>) at /usr/src/debug/hip-runtime/rocm-systems-rocm-7.2.3/projects/clr/rocclr/device/rocm/rocvirtual.cpp:1190
#11 0x00007fff61460699 in amd::roc::VirtualGPU::submitKernelInternal (this=this@entry=0x555574274b00, sizes=..., kernel=..., parameters=0x555588792300 "\b\001", event_handle=event_handle@entry=0x55558879a550, 
    sharedMemBytes=<optimized out>, vcmd=<optimized out>, aql_packet=<optimized out>, attach_signal=<optimized out>)
    at /usr/src/debug/hip-runtime/rocm-systems-rocm-7.2.3/projects/clr/rocclr/device/rocm/rocvirtual.cpp:3871
#12 0x00007fff61460f8e in amd::roc::VirtualGPU::submitKernel (this=0x555574274b00, vcmd=...) at /usr/src/debug/hip-runtime/rocm-systems-rocm-7.2.3/projects/clr/rocclr/device/rocm/rocvirtual.cpp:3972
#13 0x00007fff61422b35 in amd::Command::enqueue (this=0x55558879a540) at /usr/src/debug/hip-runtime/rocm-systems-rocm-7.2.3/projects/clr/rocclr/platform/command.cpp:406
#14 0x00007fff612a1467 in hip::ihipModuleLaunchKernel (f=0x5555856bb160, launch_params=..., hStream=<optimized out>, kernelParams=kernelParams@entry=0x7fffffffb0a0, extra=extra@entry=0x0, 
    startEvent=startEvent@entry=0x0, stopEvent=0x0, flags=0, params=0, gridId=0, numGrids=0, prevGridSum=0, allGridSum=0, firstDevice=0)
    at /usr/src/debug/hip-runtime/rocm-systems-rocm-7.2.3/projects/clr/hipamd/src/hip_module.cpp:521
#15 0x00007fff612f56b3 in hip::ihipLaunchKernel (hostFunction=0x7fffd97e1798, gridDim=..., blockDim=..., args=0x7fffffffb0a0, sharedMemBytes=0, stream=<optimized out>, startEvent=0x0, stopEvent=0x0, flags=0)
    at /usr/src/debug/hip-runtime/rocm-systems-rocm-7.2.3/projects/clr/hipamd/src/hip_platform.cpp:722
#16 0x00007fff612a07a2 in hip::hipLaunchKernel_common (hostFunction=<optimized out>, hostFunction@entry=0x7fffd97e1798, gridDim=..., blockDim=..., args=<optimized out>, args@entry=0x7fffffffb0a0, 
    sharedMemBytes=<optimized out>, stream=<optimized out>) at /usr/src/debug/hip-runtime/rocm-systems-rocm-7.2.3/projects/clr/hipamd/src/hip_module.cpp:819
#17 0x00007fff612ba374 in hip::hipLaunchKernel (hostFunction=<optimized out>, gridDim=..., blockDim=..., args=0x7fffffffb0a0, sharedMemBytes=<optimized out>, stream=<optimized out>)
    at /usr/src/debug/hip-runtime/rocm-systems-rocm-7.2.3/projects/clr/hipamd/src/hip_module.cpp:826
#18 0x00007fff608d94ca in rocprofiler::hip::hip_api_impl<1ul, 214ul>::exec<hipError_t (*&)(void const*, dim3, dim3, void**, unsigned long, ihipStream_t*), void const*, dim3, dim3, void**, unsigned long, ihipStream_t*> (_func=<optimized out>) at /usr/src/debug/rocprofiler/rocm-systems/projects/rocprofiler-sdk/source/lib/rocprofiler-sdk/hip/hip.cpp:172
#19 0x00007fff60b7b67f in rocprofiler::hip::hip_api_impl<1ul, 214ul>::functor<hipError_t, void const*, dim3, dim3, void**, unsigned long, ihipStream_t*> ()
    at /usr/src/debug/rocprofiler/rocm-systems/projects/rocprofiler-sdk/source/lib/rocprofiler-sdk/hip/hip.def.cpp:301
#20 0x00007fff60c042f1 in rocprofiler::hip::stream::create_read_functor<1ul, 214ul, hipError_t, void const*, dim3, dim3, void**, unsigned long, ihipStream_t*, hipError_t (*)(void const*, dim3, dim3, void**, unsigned long, ihipStream_t*)>(hipError_t (*)(void const*, dim3, dim3, void**, unsigned long, ihipStream_t*))::{lambda(void const*, dim3, dim3, void**, unsigned long, ihipStream_t*)#1}::operator()(void const*, dim3, dim3, void**, unsigned long, ihipStream_t*) const (args#0=0x7fffd97e1798, args#1=..., args#2=..., args#3=0x7fffffffb0a0, args#4=0, args#5=0x0, __closure=<optimized out>)
    at /usr/src/debug/rocprofiler/rocm-systems/projects/rocprofiler-sdk/source/lib/rocprofiler-sdk/hip/stream.cpp:383
#21 0x00007fffc2b6ce6b in ?? () from /usr/lib/libtorch_hip.so
#22 0x00007fffc2b64487 in ?? () from /usr/lib/libtorch_hip.so
#23 0x00007fffc2b348e4 in ?? () from /usr/lib/libtorch_hip.so
#24 0x00007fffdbb93d58 in at::native::structured_clamp_out::impl(at::Tensor const&, c10::OptionalRef<c10::Scalar>, c10::OptionalRef<c10::Scalar>, at::Tensor const&) () from /usr/lib/libtorch_cpu.so
#25 0x00007fffc3aaaecd in ?? () from /usr/lib/libtorch_hip.so
#26 0x00007fffc3aaafc7 in ?? () from /usr/lib/libtorch_hip.so
#27 0x00007fffdc6d0293 in at::_ops::clamp::call(at::Tensor const&, std::optional<c10::Scalar> const&, std::optional<c10::Scalar> const&) () from /usr/lib/libtorch_cpu.so
#28 0x00007fffe9f86faf in ?? () from /usr/lib/python3.14/site-packages/torch/lib/libtorch_python.so
#29 0x00007ffff79ddd9f in method_vectorcall_VARARGS_KEYWORDS (func=0x7ffff3bf4f40, args=0x7fffffffbf08, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/descrobject.c:359
#30 0x00007ffff79a6f3d in _PyObject_VectorcallTstate (tstate=0x7ffff7e142a0 <_PyRuntime+315680>, callable=0x7ffff3bf4f40, args=0x7fffffffbf08, nargsf=9223372036854775809, kwnames=0x7ffe4bac3840)
    at ./Include/internal/pycore_call.h:177
#31 PyObject_Vectorcall (callable=0x7ffff3bf4f40, args=0x7fffffffbf08, nargsf=9223372036854775809, kwnames=0x7ffe4bac3840) at Objects/call.c:327
#32 0x00007ffff7867e21 in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x7ffff7f6bf18, throwflag=<optimized out>) at Python/generated_cases.c.h:3229
#33 0x00007ffff79e24eb in _PyEval_EvalFrame (throwflag=0, tstate=0x7ffff7e142a0 <_PyRuntime+315680>, frame=0x7ffff7f6bc68) at ./Include/internal/pycore_ceval.h:120
#34 _PyEval_Vector (locals=0x0, tstate=0x7ffff7e142a0 <_PyRuntime+315680>, func=<optimized out>, args=<optimized out>, argcount=1, kwnames=<optimized out>) at Python/ceval.c:2110
#35 _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:413
#36 0x00007ffff7a3431e in _PyObject_VectorcallTstate (tstate=0x7ffff7e142a0 <_PyRuntime+315680>, callable=0x7ffe4bb0e400, args=0x7ffe381c0ab0, nargsf=1, kwnames=0x7ffe384d2640)
    at ./Include/internal/pycore_call.h:177
#37 _PyObject_VectorcallPrepend (tstate=0x7ffff7e142a0 <_PyRuntime+315680>, callable=0x7ffe4bb0e400, arg=<optimized out>, args=0x7ffe381c0ab8, nargsf=<optimized out>, kwnames=0x7ffe384d2640) at Objects/call.c:844
#38 method_vectorcall (method=<optimized out>, args=0x7ffe381c0ab8, nargsf=<optimized out>, kwnames=0x7ffe384d2640) at Objects/classobject.c:54
#39 0x00007ffff79fd729 in _PyVectorcall_Call (tstate=0x7ffff7e142a0 <_PyRuntime+315680>, func=0x7ffff7a341c0 <method_vectorcall>, callable=0x7ffe33f286c0, tuple=<optimized out>, kwargs=<optimized out>)
    at Objects/call.c:285
#40 _PyObject_Call (tstate=0x7ffff7e142a0 <_PyRuntime+315680>, callable=0x7ffe33f286c0, args=<optimized out>, kwargs=<optimized out>) at Objects/call.c:348
#41 0x00007ffff78650fd in PyObject_Call (callable=0x7ffe33f286c0, args=0x7ffff7ddd390 <_PyRuntime+90640>, kwargs=0x7ffe33f28700) at Objects/call.c:373
#42 PyCFunction_Call (callable=0x7ffe33f286c0, args=0x7ffff7ddd390 <_PyRuntime+90640>, kwargs=0x7ffe33f28700) at Objects/call.c:381
#43 _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x7ffff7f6bb78, throwflag=<optimized out>) at Python/generated_cases.c.h:2656
#44 0x00007ffff79e24eb in _PyEval_EvalFrame (throwflag=0, tstate=0x7ffff7e142a0 <_PyRuntime+315680>, frame=0x7ffff7f6bb78) at ./Include/internal/pycore_ceval.h:120
#45 _PyEval_Vector (locals=0x0, tstate=0x7ffff7e142a0 <_PyRuntime+315680>, func=<optimized out>, args=<optimized out>, argcount=1, kwnames=<optimized out>) at Python/ceval.c:2110
#46 _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:413
#47 0x00007ffff7a3431e in _PyObject_VectorcallTstate (tstate=0x7ffff7e142a0 <_PyRuntime+315680>, callable=0x7ffeae3c6b90, args=0x7ffe381c39f0, nargsf=1, kwnames=0x7ffe384d3340)
    at ./Include/internal/pycore_call.h:177
#48 _PyObject_VectorcallPrepend (tstate=0x7ffff7e142a0 <_PyRuntime+315680>, callable=0x7ffeae3c6b90, arg=<optimized out>, args=0x7ffe381c39f8, nargsf=<optimized out>, kwnames=0x7ffe384d3340) at Objects/call.c:844
#49 method_vectorcall (method=<optimized out>, args=0x7ffe381c39f8, nargsf=<optimized out>, kwnames=0x7ffe384d3340) at Objects/classobject.c:54
#50 0x00007ffff79fd729 in _PyVectorcall_Call (tstate=0x7ffff7e142a0 <_PyRuntime+315680>, func=0x7ffff7a341c0 <method_vectorcall>, callable=0x7ffe33f28280, tuple=<optimized out>, kwargs=<optimized out>)
    at Objects/call.c:285
#51 _PyObject_Call (tstate=0x7ffff7e142a0 <_PyRuntime+315680>, callable=0x7ffe33f28280, args=<optimized out>, kwargs=<optimized out>) at Objects/call.c:348
#52 0x00007ffff78650fd in PyObject_Call (callable=0x7ffe33f28280, args=0x7ffff7ddd390 <_PyRuntime+90640>, kwargs=0x7ffe33f28200) at Objects/call.c:373
#53 PyCFunction_Call (callable=0x7ffe33f28280, args=0x7ffff7ddd390 <_PyRuntime+90640>, kwargs=0x7ffe33f28200) at Objects/call.c:381
#54 _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x7ffff7f6bae8, throwflag=<optimized out>) at Python/generated_cases.c.h:2656
#55 0x00007ffff79e24eb in _PyEval_EvalFrame (throwflag=0, tstate=0x7ffff7e142a0 <_PyRuntime+315680>, frame=0x7ffff7f6bae8) at ./Include/internal/pycore_ceval.h:120
#56 _PyEval_Vector (locals=0x0, tstate=0x7ffff7e142a0 <_PyRuntime+315680>, func=<optimized out>, args=<optimized out>, argcount=1, kwnames=<optimized out>) at Python/ceval.c:2110
#57 _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:413
#58 0x00007ffff7b23b12 in _PyObject_VectorcallDictTstate (tstate=<optimized out>, callable=0x7ffeae3c6ae0, args=0x7fffffffcb50, nargsf=1, kwargs=<optimized out>) at Objects/call.c:146
#59 _PyObject_Call_Prepend (tstate=<optimized out>, callable=0x7ffeae3c6ae0, obj=<optimized out>, args=<optimized out>, kwargs=<optimized out>) at Objects/call.c:504
#60 call_method (self=<optimized out>, attr=<optimized out>, args=<optimized out>, kwds=<optimized out>) at Objects/typeobject.c:3000
#61 slot_tp_call (self=<optimized out>, args=<optimized out>, kwds=<optimized out>) at Objects/typeobject.c:10326
#62 0x00007ffff79a48c9 in _PyObject_MakeTpCall (tstate=0x7ffff7e142a0 <_PyRuntime+315680>, callable=0x7ffe38599d30, args=0x7fffffffce08, nargs=<optimized out>, keywords=0x7ffe4bc2b740) at Objects/call.c:242
#63 0x00007ffff7868ce4 in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x7ffff7f6b8f0, throwflag=<optimized out>) at Python/generated_cases.c.h:2961
#64 0x00007ffff79e24eb in _PyEval_EvalFrame (throwflag=0, tstate=0x7ffff7e142a0 <_PyRuntime+315680>, frame=0x7ffff7f6b6a0) at ./Include/internal/pycore_ceval.h:120
#65 _PyEval_Vector (locals=0x0, tstate=0x7ffff7e142a0 <_PyRuntime+315680>, func=<optimized out>, args=<optimized out>, argcount=3, kwnames=<optimized out>) at Python/ceval.c:2110
#66 _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:413
#67 0x00007ffff7a34291 in _PyObject_VectorcallTstate (tstate=0x7ffff7e142a0 <_PyRuntime+315680>, callable=0x7ffe4bc4ddd0, args=0x7fffffffd000, nargsf=<optimized out>, kwnames=0x0)
    at ./Include/internal/pycore_call.h:177
#68 _PyObject_VectorcallPrepend (tstate=0x7ffff7e142a0 <_PyRuntime+315680>, callable=0x7ffe4bc4ddd0, arg=<optimized out>, args=<optimized out>, nargsf=<optimized out>, kwnames=0x0) at Objects/call.c:874
#69 method_vectorcall (method=<optimized out>, args=<optimized out>, nargsf=<optimized out>, kwnames=0x0) at Objects/classobject.c:54
#70 0x00007ffff78650fd in PyObject_Call (callable=0x7ffe4c722540, args=0x7ffe4bc50940, kwargs=0x7ffe381c5ec0) at Objects/call.c:373
#71 PyCFunction_Call (callable=0x7ffe4c722540, args=0x7ffe4bc50940, kwargs=0x7ffe381c5ec0) at Objects/call.c:381
#72 _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x7ffff7f6b5f0, throwflag=<optimized out>) at Python/generated_cases.c.h:2656
#73 0x00007ffff79e24eb in _PyEval_EvalFrame (throwflag=0, tstate=0x7ffff7e142a0 <_PyRuntime+315680>, frame=0x7ffff7f6b5f0) at ./Include/internal/pycore_ceval.h:120
#74 _PyEval_Vector (locals=0x0, tstate=0x7ffff7e142a0 <_PyRuntime+315680>, func=<optimized out>, args=<optimized out>, argcount=4, kwnames=<optimized out>) at Python/ceval.c:2110
#75 _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:413
#76 0x00007ffff7a34291 in _PyObject_VectorcallTstate (tstate=0x7ffff7e142a0 <_PyRuntime+315680>, callable=0x7ffe4ba5c9e0, args=0x7fffffffd460, nargsf=<optimized out>, kwnames=0x0)
    at ./Include/internal/pycore_call.h:177
#77 _PyObject_VectorcallPrepend (tstate=0x7ffff7e142a0 <_PyRuntime+315680>, callable=0x7ffe4ba5c9e0, arg=<optimized out>, args=<optimized out>, nargsf=<optimized out>, kwnames=0x0) at Objects/call.c:874
#78 method_vectorcall (method=<optimized out>, args=<optimized out>, nargsf=<optimized out>, kwnames=0x0) at Objects/classobject.c:54
#79 0x00007ffff78650fd in PyObject_Call (callable=0x7ffe4bc47900, args=0x7ffe8b8ebf60, kwargs=0x7ffe4bad8a00) at Objects/call.c:373
#80 PyCFunction_Call (callable=0x7ffe4bc47900, args=0x7ffe8b8ebf60, kwargs=0x7ffe4bad8a00) at Objects/call.c:381
#81 _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x7ffff7f6b518, throwflag=<optimized out>) at Python/generated_cases.c.h:2656
#82 0x00007ffff79b6d72 in _PyEval_EvalFrame (throwflag=0, tstate=0x7ffff7e142a0 <_PyRuntime+315680>, frame=<optimized out>) at ./Include/internal/pycore_ceval.h:120
#83 _PyEval_Vector.constprop.0 (tstate=tstate@entry=0x7ffff7e142a0 <_PyRuntime+315680>, func=func@entry=0x7ffff6c2b3d0, locals=locals@entry=0x7ffff6c31580, kwnames=0x0, argcount=0, args=0x0) at Python/ceval.c:2110
#84 0x00007ffff7aba2c4 in PyEval_EvalCode (co=0x7ffff6c4e630, globals=<optimized out>, locals=0x7ffff6c31580) at Python/ceval.c:982
#85 0x00007ffff7b0398f in run_mod (mod=<optimized out>, filename=<optimized out>, globals=0x7ffff6c31580, locals=0x7ffff6c31580, flags=<optimized out>, arena=0x7ffff6d1be10, interactive_src=0x7ffff6c43eb0, 
    generate_new_source=0) at Python/pythonrun.c:1460
#86 0x00007ffff7a453a7 in _PyRun_StringFlagsWithName.constprop.0 (str=str@entry=0x7ffff6cdc050 "from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=23)\n", 
    name=name@entry=0x7ffff6c315f0, globals=globals@entry=0x7ffff6c31580, locals=locals@entry=0x7ffff6c31580, flags=flags@entry=0x7fffffffdac8, generate_new_source=0, start=257) at Python/pythonrun.c:1260
#87 0x00007ffff7afb85e in _PyRun_SimpleStringFlagsWithName (command=0x7ffff6cdc050 "from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=6, pipe_handle=23)\n", name=<optimized out>, 
    flags=0x7fffffffdac8) at Python/pythonrun.c:578
#88 0x00007ffff7aa7aef in pymain_run_command (command=<optimized out>) at Modules/main.c:261
#89 pymain_run_python (exitcode=0x7fffffffdabc) at Modules/main.c:686
#90 Py_RunMain () at Modules/main.c:776
#91 0x00007ffff7aa167c in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:830
#92 0x00007ffff7427741 in __libc_start_call_main (main=main@entry=0x555555555120 <main>, argc=argc@entry=4, argv=argv@entry=0x7fffffffdd38) at ../sysdeps/nptl/libc_start_call_main.h:59
#93 0x00007ffff7427879 in __libc_start_main_impl (main=0x555555555120 <main>, argc=4, argv=0x7fffffffdd38, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdd28)
    at ../csu/libc-start.c:360
#94 0x0000555555555045 in _start ()
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://vllm-omni.readthedocs.io), which can answer lots of frequently asked questions.

**Comment by davispuh** [comment]
Just tried with latest ROCm git develop and it works there without failure. Maybe this ROCm/rocm-system@559d48b1f013a2a8e9decd2557508de7ac6c6b10 commit fixed it. It's not in any release so need to wait for next ROCm release.

**Comment by Gaohan123** [comment]
@tjtanaa PTAL. Thanks

**Comment by tjtanaa** [comment]
@davispuh can you use the `vllm/vllm-openai-rocm:v0.21.0` docker image as base and see if you still encounter this issue? I don't have the Radeon GPU to test this.

**Comment by davispuh** [comment]
> [@davispuh](https://github.com/davispuh) can you use the `vllm/vllm-openai-rocm:v0.21.0` docker image as base and see if you still encounter this issue? I don't have the Radeon GPU to test this.

This crash is with OmniVoice which is not present in `vllm/vllm-openai-rocm:v0.21.0` image so not sure how I'm meant to test with it.
But I tested `vllm/vllm-omni-rocm:v0.20.0` image:
```
$ podman run --device /dev/kfd:/dev/kfd --device /dev/dri:/dev/dri --ipc=host --group-add keep-groups --entrypoint python vllm/vllm-omni-rocm:v0.20.0 /app/vllm-omni/examples/offline_inference/text_to_speech/omnivoice/end2end.py --stage-config /app/vllm-omni/vllm_omni/model_executor/stage_configs/omnivoice.yaml
```
which fails for me with:
```
MIOpen Error: 7914c4ea3e44:/longer_pathname_so_that_rpms_can_support_packaging_the_debug_info_for_all_os_profiles/src/rocm-libraries/projects/miopen/src/ocl/convolutionocl.cpp:1151: No suitable algorithm was found to execute the required convolution
```

Then I added 
```py
import torch
torch.backends.cudnn.enabled = False
```
to `end2end.py` and it worked fine without any crashes.

**Comment by akshatvishu** [comment]
I tested using the current vLLM-Omni ROCm Dockerfile  and its working fine  out of the box! @tjtanaa 

Environment :
```bash
- AMD Dev Cloud, 1x MI300X / gfx942
- Base image: vllm/vllm-openai-rocm:v0.21.0
- vLLM: 0.21.0
- vLLM-Omni: current branch installed editable from /app/vllm-omni
- VLLM_WORKER_MULTIPROC_METHOD=spawn
- VLLM_ROCM_USE_AITER=0 
```
<details>
<summary>`python collect_env.py`</summary>

==============================
        System Info
==============================
OS                           : Ubuntu 22.04.5 LTS (x86_64)
GCC version                  : (Ubuntu 11.4.0-1ubuntu1~22.04.3) 11.4.0
Clang version                : 22.0.0git (https://github.com/RadeonOpenCompute/llvm-project roc-7.2.2 26084 f58b06dce1f9c15707c5f808fd002e18c2accf7e)
CMake version                : version 3.31.10
Libc version                 : glibc-2.35

==============================
       PyTorch Info
==============================
PyTorch version              : 2.10.0+git8514f05
Is debug build               : False
CUDA used to build PyTorch   : N/A
ROCM used to build PyTorch   : 7.2.53211

==============================
      Python Environment
==============================
Python version               : 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0] (64-bit runtime)
Python platform              : Linux-6.8.0-106-generic-x86_64-with-glibc2.35

==============================
       CUDA / GPU Info
==============================
Is CUDA available            : True
CUDA runtime version         : Could not collect
CUDA_MODULE_LOADING set to   : 
GPU models and configuration :  (gfx942:sramecc+:xnack-)
Nvidia driver version        : Could not collect
cuDNN version                : Could not collect
HIP runtime version          : 7.2.53211
MIOpen runtime version       : 3.5.1
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                            x86_64
CPU op-mode(s):                          32-bit, 64-bit
Address sizes:                           46 bits physical, 57 bits virtual
Byte Order:                              Little Endian
CPU(s):                                  20
On-line CPU(s) list:                     0-19
Vendor ID:                               GenuineIntel
Model name:                              INTEL(R) XEON(R) PLATINUM 8568Y+
CPU family:                              6
Model:                                   207
Thread(s) per core:                      1
Core(s) per socket:                      20
Socket(s):                               1
Stepping:                                2
BogoMIPS:                                4600.00
Flags:                                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq dtes64 vmx ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx_vnni avx512_bf16 wbnoinvd arat vnmi avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b fsrm md_clear serialize tsxldtrk avx512_fp16 arch_capabilities
Virtualization:                          VT-x
Hypervisor vendor:                       KVM
Virtualization type:                     full
L1d cache:                               640 KiB (20 instances)
L1i cache:                               640 KiB (20 instances)
L2 cache:                                80 MiB (20 instances)
NUMA node(s):                            1
NUMA node0 CPU(s):                       0-19
Vulnerability Gather data sampling:      Not affected
Vulnerability Indirect target selection: Vulnerable
Vulnerability Itlb multihit:             Not affected
Vulnerability L1tf:                      Not affected
Vulnerability Mds:                       Not affected
Vulnerability Meltdown:                  Not affected
Vulnerability Mmio stale data:           Unknown: No mitigations
Vulnerability Reg file data sampling:    Not affected
Vulnerability Retbleed:                  Not affected
Vulnerability Spec rstack overflow:      Not affected
Vulnerability Spec store bypass:         Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:                Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:                Mitigation; Enhanced / Automatic IBRS; IBPB conditional; PBRSB-eIBRS SW sequence; BHI SW loop, KVM SW loop
Vulnerability Srbds:                     Not affected
Vulnerability Tsa:                       Not affected
Vulnerability Tsx async abort:           Mitigation; TSX disabled
Vulnerability Vmscape:                   Not affected

==============================
Versions of relevant libraries
==============================
[pip3] conch-triton-kernels==1.2.1
[pip3] mypy==1.11.1
[pip3] mypy_extensions==1.1.0
[pip3] numpy==2.1.3
[pip3] onnx==1.19.0
[pip3] onnx-ir==0.2.1
[pip3] onnxruntime-rocm==1.22.2.post1
[pip3] onnxscript==0.7.0
[pip3] onnxslim==0.1.93
[pip3] pyzmq==27.1.0
[pip3] torch==2.10.0+git8514f05
[pip3] torch_c_dlpack_ext==0.1.5
[pip3] torch-complex==0.4.4
[pip3] torch-einops-utils==0.1.1
[pip3] torchaudio==2.9.0+eaa9e4e
[pip3] torchcodec==0.13.0
[pip3] torchdiffeq==0.2.5
[pip3] torchmetrics==1.9.0
[pip3] torchsde==0.2.6
[pip3] torchvision==0.24.1+d801a34
[pip3] transformers==5.8.1
[pip3] triton==3.6.0
[pip3] triton_kernels==1.0.0
[pip3] x-transformers==2.19.7
[conda] Could not collect

==============================
         vLLM Info
==============================
ROCM Version                 : 7.2.53211-35e8c7bf89
vLLM Version                 : 0.21.0
vLLM-Omni Version            : 0.1.dev1734+g9abf9545d.rocm (git sha: 9abf9545d, date: ocm)
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled
GPU Topology:
  ============================ ROCm System Management Interface ============================
================================ Weight between two GPUs =================================
       GPU0         
GPU0   0            

================================= Hops between two GPUs ==================================
       GPU0         
GPU0   0            

=============================== Link Type between two GPUs ===============================
       GPU0         
GPU0   0            

======================================= Numa Nodes =======================================
GPU[0]          : (Topology) Numa Node: 0
GPU[0]          : (Topology) Numa Affinity: 0
================================== End of ROCm SMI Log ===================================

==============================
     Environment Variables
==============================
VLLM_WORKER_MULTIPROC_METHOD=spawn
VLLM_ROCM_USE_AITER=0
PYTORCH_ROCM_ARCH=gfx942
LD_LIBRARY_PATH=/usr/local/lib/python3.12/dist-packages/cv2/../../lib64:/opt/rocm/lib:/usr/local/lib:
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_root
</details>





### cmd

```bash
python examples/offline_inference/text_to_speech/omnivoice/end2end.py \
  --model k2-fsa/OmniVoice \
  --stage-config vllm_omni/deploy/omnivoice.yaml \
  --text "Hello, this is a test of OmniVoice running on AMD MI300X with vLLM-Omni." \
  --output /workspace/outputs/omnivoice/omnivoice_basic.wav \
  2>&1 | tee /workspace/outputs/omnivoice/run.log
```
<details>
<summary>log</summary>
```bash
/app/vllm-omni/vllm_omni/version.py:55: RuntimeWarning: vLLM and vLLM-Omni appear to have mismatched major/minor versions:
 --> vLLM-Omni version 0.1.dev1734+g9abf9545d.rocm
 --> vLLM version 0.21.0
This will likely cause compatibility issues.
  warn_if_misaligned_vllm_version()
[aiter] import [module_aiter_core] under /usr/local/lib/python3.12/dist-packages/aiter/jit/module_aiter_core.so
Initializing OmniVoice with model=k2-fsa/OmniVoice
INFO 05-30 11:22:15 [weight_utils.py:50] Using model weights format ['*']
INFO 05-30 11:22:18 [weight_utils.py:82] Time spent downloading weights for k2-fsa/OmniVoice: 3.586819 seconds
INFO 05-30 11:22:18 [omni_base.py:172] [Omni] Initializing with model k2-fsa/OmniVoice
INFO 05-30 11:22:18 [async_omni_engine.py:276] [AsyncOmniEngine] Initializing with model k2-fsa/OmniVoice
WARNING 05-30 11:22:18 [utils.py:602] --stage-configs-path is deprecated; migrate 'vllm_omni/deploy/omnivoice.yaml' and use --deploy-config.
INFO 05-30 11:22:18 [async_omni_engine.py:360] [AsyncOmniEngine] Launching Orchestrator thread with 1 stages
INFO 05-30 11:22:18 [initialization.py:364] Loaded OmniTransferConfig with 0 connector configurations
INFO 05-30 11:22:18 [stage_init_utils.py:632] [stage_init] Stage-0 set runtime devices: 0
INFO 05-30 11:22:19 [multiproc_executor.py:138] Starting server...
/app/vllm-omni/vllm_omni/version.py:55: RuntimeWarning: vLLM and vLLM-Omni appear to have mismatched major/minor versions:
 --> vLLM-Omni version 0.1.dev1734+g9abf9545d.rocm
 --> vLLM version 0.21.0
This will likely cause compatibility issues.
  warn_if_misaligned_vllm_version()
[aiter] import [module_aiter_core] under /usr/local/lib/python3.12/dist-packages/aiter/jit/module_aiter_core.so
INFO 05-30 11:22:26 [diffusion_worker.py:680] Worker 0 created result MessageQueue
INFO 05-30 11:22:26 [scheduler.py:239] Chunked prefill is enabled with max_num_batched_tokens=2048.
INFO 05-30 11:22:26 [vllm.py:886] Asynchronous scheduling is enabled.
INFO 05-30 11:22:26 [kernel.py:212] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
INFO 05-30 11:22:26 [diffusion_worker.py:236] Final IR op priority after setting vLLM-Omni overrides: IrOpPriorityConfig(rms_norm=['vllm_c', 'native'], fused_add_rms_norm=['vllm_c', 'native'])
[rank0]:[W530 11:22:26.959359454 ProcessGroupGloo.cpp:523] Warning: Unable to resolve hostname to a (local) address. Using the loopback address as fallback. Manually set the network interface to bind to with GLOO_SOCKET_IFNAME. (function operator())
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 05-30 11:22:26 [diffusion_worker.py:247] Worker 0: Initialized device and distributed environment.
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 05-30 11:22:26 [parallel_state.py:588] Building SP subgroups from explicit sp_group_ranks (sp_size=1, ulysses=1, ring=1, use_ulysses_low=True).
INFO 05-30 11:22:26 [parallel_state.py:630] SP group details for rank 0: sp_group=[0], ulysses_group=[0], ring_group=[0]
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0

Fetching 13 files:   0%|          | 0/13 [00:00<?, ?it/s]
Fetching 13 files: 100%|██████████| 13/13 [00:00<00:00, 37526.46it/s]

Loading weights:   0%|          | 0/527 [00:00<?, ?it/s]
Loading weights:  41%|████▏     | 218/527 [00:00<00:00, 2158.44it/s]
Loading weights:  82%|████████▏ | 434/527 [00:00<00:00, 1834.05it/s]
Loading weights: 100%|██████████| 527/527 [00:00<00:00, 1765.84it/s]
INFO 05-30 11:22:28 [pipeline_omnivoice.py:97] HiggsAudioV2 tokenizer loaded for voice cloning on cuda:0
INFO 05-30 11:22:28 [speaker_cache.py:45] Speaker cache ready (max_bytes=536870912)
INFO 05-30 11:22:29 [omnivoice_generator.py:1003] Generator: 312/313 weights loaded, 1 skipped (decoder weights)
INFO 05-30 11:22:29 [omnivoice_generator.py:551] OmniVoice CUDA Graph warmup: capturing 10 bucket sizes [128, 192, 256, 320, 384, 448, 512, 640, 768, 1024]
INFO 05-30 11:22:34 [omnivoice_generator.py:544] OmniVoice CUDA Graph captured for key (2, 128)
INFO 05-30 11:22:34 [omnivoice_generator.py:544] OmniVoice CUDA Graph captured for key (2, 192)
INFO 05-30 11:22:34 [omnivoice_generator.py:544] OmniVoice CUDA Graph captured for key (2, 256)
INFO 05-30 11:22:34 [omnivoice_generator.py:544] OmniVoice CUDA Graph captured for key (2, 320)
INFO 05-30 11:22:34 [omnivoice_generator.py:544] OmniVoice CUDA Graph captured for key (2, 384)
INFO 05-30 11:22:34 [omnivoice_generator.py:544] OmniVoice CUDA Graph captured for key (2, 448)
INFO 05-30 11:22:34 [omnivoice_generator.py:544] OmniVoice CUDA Graph captured for key (2, 512)
INFO 05-30 11:22:34 [omnivoice_generator.py:544] OmniVoice CUDA Graph captured for key (2, 640)
INFO 05-30 11:22:34 [omnivoice_generator.py:544] OmniVoice CUDA Graph captured for key (2, 768)
INFO 05-30 11:22:34 [omnivoice_generator.py:544] OmniVoice CUDA Graph captured for key (2, 1024)
INFO 05-30 11:22:34 [omnivoice_generator.py:564] OmniVoice CUDA Graph warmup complete (10 graphs)
INFO 05-30 11:22:36 [omnivoice_decoder.py:213] Loaded OmniVoice decoder: 8 quantizers, fc2(1024→256), acoustic decoder (110 weights)
INFO 05-30 11:22:36 [pipeline_omnivoice.py:323] OmniVoice pipeline loaded on cuda:0
INFO 05-30 11:22:36 [diffusers_loader.py:375] Loading weights took 1633.66 seconds
INFO 05-30 11:22:36 [diffusion_model_runner.py:144] Model loading took 3.5557 GiB and 10.034098 seconds
INFO 05-30 11:22:36 [diffusion_model_runner.py:149] Model runner: Model loaded successfully.
INFO 05-30 11:22:36 [diffusion_model_runner.py:190] Model runner: Initialization complete.
WARNING 05-30 11:22:36 [gpu_memory_utils.py:88] NVML init failed, will use profiling fallback: NVML Shared Library Not Found
INFO 05-30 11:22:36 [manager.py:96] Initializing DiffusionLoRAManager: device=cuda:0, dtype=torch.float32, max_cached_adapters=1, static_lora_path=None
INFO 05-30 11:22:36 [diffusion_worker.py:206] Worker 0: Initialization complete.
INFO 05-30 11:22:36 [diffusion_worker.py:851] Worker 0: Scheduler loop started.
INFO 05-30 11:22:36 [diffusion_worker.py:753] Worker 0 ready to receive requests via shared memory
INFO 05-30 11:22:36 [diffusion_engine.py:711] dummy run to warm up the model
INFO 05-30 11:22:40 [inline_stage_diffusion_client.py:72] [InlineStageDiffusionClient] stage-0 [rep-0] initialized inline (batch_size=1)
INFO 05-30 11:22:40 [async_omni_engine.py:1094] [AsyncOmniEngine] Stage 0 replica 0 initialized (diffusion, batch_size=1, devices=0)
INFO 05-30 11:22:40 [orchestrator.py:220] [Orchestrator] Starting event loop
INFO 05-30 11:22:40 [async_omni_engine.py:387] [AsyncOmniEngine] Orchestrator ready with 1 stages
INFO 05-30 11:22:40 [omni_base.py:185] [Omni] AsyncOmniEngine initialized in 21.61 seconds
INFO 05-30 11:22:40 [omni_base.py:202] [Omni] Initialized with 1 stages for model k2-fsa/OmniVoice
Model initialized. Preparing inputs...
Generating speech for: Hello, this is a test of OmniVoice running on AMD MI300X with vLLM-Omni.

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.17it/s]INFO 05-30 11:22:41 [stats.py:513] 
INFO 05-30 11:22:41 [stats.py:513] [Overall Summary]
INFO 05-30 11:22:41 [stats.py:513] +-----------------------------+---------+
INFO 05-30 11:22:41 [stats.py:513] | Field                       |   Value |
INFO 05-30 11:22:41 [stats.py:513] +-----------------------------+---------+
INFO 05-30 11:22:41 [stats.py:513] | e2e_requests                |       1 |
INFO 05-30 11:22:41 [stats.py:513] | e2e_wall_time_ms            | 854.596 |
INFO 05-30 11:22:41 [stats.py:513] | e2e_avg_time_per_request_ms | 854.596 |
INFO 05-30 11:22:41 [stats.py:513] | e2e_stage_0_wall_time_ms    | 854.508 |
INFO 05-30 11:22:41 [stats.py:513] +-----------------------------+---------+
INFO 05-30 11:22:41 [stats.py:539] 
INFO 05-30 11:22:41 [stats.py:539] [RequestE2EStats [request_id=0_2414a9fa-9df6-4085-a4f6-d0b15e47f9ce]]
INFO 05-30 11:22:41 [stats.py:539] +--------------+---------+
INFO 05-30 11:22:41 [stats.py:539] | Field        |   Value |
INFO 05-30 11:22:41 [stats.py:539] +--------------+---------+
INFO 05-30 11:22:41 [stats.py:539] | e2e_total_ms | 854.508 |
INFO 05-30 11:22:41 [stats.py:539] +--------------+---------+
INFO 05-30 11:22:41 [stats.py:580] [OmniTiming] req=0_2414a9fa-9df6-4085-a4f6-d0b15e47f9ce total=0.85s engine=0.85s stages=[0:0.85s]
INFO 05-30 11:22:41 [stats.py:622] 
INFO 05-30 11:22:41 [stats.py:622] [StageRequestStats [request_id=0_2414a9fa-9df6-4085-a4f6-d0b15e47f9ce]]
INFO 05-30 11:22:41 [stats.py:622] +-------------------+---------+
INFO 05-30 11:22:41 [stats.py:622] | Field             |       0 |
INFO 05-30 11:22:41 [stats.py:622] +-------------------+---------+
INFO 05-30 11:22:41 [stats.py:622] | batch_id          |       1 |
INFO 05-30 11:22:41 [stats.py:622] | batch_size        |       1 |
INFO 05-30 11:22:41 [stats.py:622] | stage_gen_time_ms | 854.128 |
INFO 05-30 11:22:41 [stats.py:622] +-------------------+---------+

Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.12it/s]
Received 1 outputs.
Multimodal output keys: dict_keys(['audio'])
Saved audio to /workspace/outputs/omnivoice/omnivoice_basic.wav (24000Hz, 4.84s)
INFO 05-30 11:22:41 [omni_base.py:467] [Omni] Shutting down
INFO 05-30 11:22:41 [async_omni_engine.py:2416] [AsyncOmniEngine] Shutting down Orchestrator
INFO 05-30 11:22:41 [orchestrator.py:351] [Orchestrator] Received shutdown signal
INFO 05-30 11:22:41 [orchestrator.py:1359] [Orchestrator] Shutting down all 1 client(s)
INFO 05-30 11:22:41 [diffusion_worker.py:793] Worker 0: Received shutdown message
INFO 05-30 11:22:41 [diffusion_worker.py:814] event loop terminated.
INFO 05-30 11:22:41 [diffusion_worker.py:859] Worker 0: Shutdown complete.
INFO 05-30 11:22:42 [stage_pool.py:776] [StagePool] Stage 0 replica 0 shut down
Done.
```
</details>

**Comment by Gaohan123** [comment]
close as solved. I can reopen if needed.

**Comment by davispuh** [comment]
Looks like it depends on ROCm build flags or something because I can still reproduce on Arch Linux with latest ROCm v7.2.4.
I also confirmed that indeed this ROCm/rocm-systems@559d48b1f013a2a8e9decd2557508de7ac6c6b10 commit fixes it but it still wasn't included in last release.
