### ISSUE TITLE
[Bug]: NPU，RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}

### ISSUE THREAD

**Issue by baiyu-123** [vllm-project/vllm-omni#424]
### Your current environment

<details>
# Update DEVICE according to your NPUs (/dev/davinci[0-7])
export DEVICE0=/dev/davinci0
export DEVICE1=/dev/davinci1
# Update the vllm-ascend image
# Atlas A2:
# export IMAGE=quay.io/ascend/vllm-ascend:v0.12.0rc1
# Atlas A3:
# export IMAGE=quay.io/ascend/vllm-ascend:v0.12.0rc1-a3
export IMAGE=quay.io/ascend/vllm-ascend:v0.12.0rc1
docker run --rm \
    --name vllm-omni-npu \
    --shm-size=1g \
    --device $DEVICE0 \
    --device $DEVICE1 \
    --device /dev/davinci_manager \
    --device /dev/devmm_svm \
    --device /dev/hisi_hdc \
    -v /usr/local/dcmi:/usr/local/dcmi \
    -v /usr/local/bin/npu-smi:/usr/local/bin/npu-smi \
    -v /usr/local/Ascend/driver/lib64/:/usr/local/Ascend/driver/lib64/ \
    -v /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info \
    -v /etc/ascend_install.info:/etc/ascend_install.info \
    -v /data/Qwen2.5-Omni-7B:/data/Qwen2.5-Omni-7B \
    -v /root/.cache:/root/.cache \
    -p 8000:8000 \
    -it $IMAGE bash

# Inside the container, install vLLM-Omni from source
cd /vllm-workspace
git clone https://github.com/vllm-project/vllm-omni.git
cd vllm-omni
pip install -v -e .
export VLLM_WORKER_MULTIPROC_METHOD=spawn

vllm serve data/Qwen2.5-Omni-7B --omni --port 8091

```text
Your output of `python collect_env.py` here
```
</details>

</error report>

### 🐛 Describe the bug

^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m ERROR 12-23 07:23:11 [core.py:708]     self.block_table = MultiGroupBlockTable(^M
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m ERROR 12-23 07:23:11 [core.py:708]                        ^^^^^^^^^^^^^^^^^^^^^^M
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m ERROR 12-23 07:23:11 [core.py:708]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/block_table.py", line 267, in __init__^M
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m ERROR 12-23 07:23:11 [core.py:708]     self.block_tables = [^M
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m ERROR 12-23 07:23:11 [core.py:708]                         ^^M
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m ERROR 12-23 07:23:11 [core.py:708]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/block_table.py", line 268, in <listcomp>^M
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m ERROR 12-23 07:23:11 [core.py:708]     BlockTable(^M
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m ERROR 12-23 07:23:11 [core.py:708]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/block_table.py", line 60, in __init__^M
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m ERROR 12-23 07:23:11 [core.py:708]     self.block_table = torch.zeros(^M
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m ERROR 12-23 07:23:11 [core.py:708]                        ^^^^^^^^^^^^^M
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m ERROR 12-23 07:23:11 [core.py:708] RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnInplaceZero.^M
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m ERROR 12-23 07:23:11 [core.py:708] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.^M
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m ERROR 12-23 07:23:11 [core.py:708] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.^M
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m ERROR 12-23 07:23:11 [core.py:708] [ERROR] 2025-12-23-07:23:11 (PID:6444, Device:0, RankID:-1) ERR00100 PTA call acl api failed.^M
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m ERROR 12-23 07:23:11 [core.py:708]
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m Process EngineCore_DP0:
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m Traceback (most recent call last):
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m   File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m     self.run()
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m   File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/process.py", line 108, in run
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m     self._target(*self._args, **self._kwargs)
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 712, in run_engine_core
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m     raise e
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 699, in run_engine_core
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m     engine_core = EngineCoreProc(*args, **kwargs)
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 498, in __init__
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m     super().__init__(vllm_config, executor_class, log_stats,
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 83, in __init__
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m     self.model_executor = executor_class(vllm_config)
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m   File "/vllm-workspace/vllm/vllm/executor/executor_base.py", line 54, in __init__
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m     self._init_executor()
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m   File "/vllm-workspace/vllm/vllm/executor/uniproc_executor.py", line 54, in _init_executor
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m     self.collective_rpc("init_device")
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m   File "/vllm-workspace/vllm/vllm/executor/uniproc_executor.py", line 83, in collective_rpc
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m     return [run_method(self.driver_worker, method, args, kwargs)]
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m   File "/vllm-workspace/vllm/vllm/utils/__init__.py", line 3122, in run_method
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m     return func(*args, **kwargs)
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m            ^^^^^^^^^^^^^^^^^^^^^
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m   File "/vllm-workspace/vllm/vllm/worker/worker_base.py", line 259, in init_device
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m     self.worker.init_device()  # type: ignore
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m     ^^^^^^^^^^^^^^^^^^^^^^^^^
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m   File "/vllm-workspace/vllm-omni/vllm_omni/worker/npu/npu_generation_worker.py", line 15, in init_device
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m     self.model_runner: NPUGenerationModelRunner = NPUGenerationModelRunner(self.vllm_config, device)
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m   File "/vllm-workspace/vllm-omni/vllm_omni/worker/npu/npu_model_runner.py", line 39, in __init__
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m     super().__init__(*args, **kwargs)
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 511, in __init__
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m     self.input_batch = InputBatch(
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m                        ^^^^^^^^^^^
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/npu_input_batch.py", line 146, in __init__
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m     self.block_table = MultiGroupBlockTable(
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m                        ^^^^^^^^^^^^^^^^^^^^^
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/block_table.py", line 267, in __init__
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m     self.block_tables = [
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m                         ^
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/block_table.py", line 268, in <listcomp>
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m     BlockTable(
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/block_table.py", line 60, in __init__
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m     self.block_table = torch.zeros(
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m                        ^^^^^^^^^^^^
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnInplaceZero.
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m [ERROR] 2025-12-23-07:23:11 (PID:6444, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
^[[1;36m(EngineCore_DP0 pid=6444)^[[0;0m
Process SpawnProcess-3:
Traceback (most recent call last):
  File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/vllm-workspace/vllm-omni/vllm_omni/entrypoints/omni_stage.py", line 739, in _stage_worker_async_entry
    asyncio.run(_stage_worker_async(omni_stage, model, stage_payload, batch_timeout))
  File "/usr/local/python3.11.13/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11.13/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11.13/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/vllm-workspace/vllm-omni/vllm_omni/entrypoints/omni_stage.py", line 833, in _stage_worker_async
    stage_engine = AsyncOmniStageLLM.from_vllm_config(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vllm-workspace/vllm/vllm/utils/__init__.py", line 1572, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/vllm-workspace/vllm-omni/vllm_omni/entrypoints/async_omni.py", line 874, in from_vllm_config
    return cls(
           ^^^^
  File "/vllm-workspace/vllm-omni/vllm_omni/entrypoints/async_omni.py", line 799, in __init__
    self.engine_core = EngineCoreClient.make_async_mp_client(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vllm-workspace/vllm/vllm/v1/engine/core_client.py", line 102, in make_async_mp_client
    return AsyncMPClient(*client_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vllm-workspace/vllm/vllm/v1/engine/core_client.py", line 769, in __init__
    super().__init__(
  File "/vllm-workspace/vllm/vllm/v1/engine/core_client.py", line 448, in __init__
    with launch_core_engines(vllm_config, executor_class,
  File "/usr/local/python3.11.13/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/vllm-workspace/vllm/vllm/v1/engine/utils.py", line 732, in launch_core_engines
    wait_for_engine_startup(
  File "/vllm-workspace/vllm/vllm/v1/engine/utils.py", line 785, in wait_for_engine_startup
    raise RuntimeError("Engine core initialization failed. "
RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
                                                                                              

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://vllm-omni.readthedocs.io), which can answer lots of frequently asked questions.

**Comment by hsliuustc0106** [comment]
I do not think we have supported with NPU with vllm 0.12.0. Please check with 0.11.0rc1 first

**Comment by hsliuustc0106** [comment]
@gcanlin PTAL

**Comment by gcanlin** [comment]
Please checkout commit `9464e14` and use vllm-ascend v0.11.0rc2 and vllm v0.11.0. We're still upgrading vllm-ascend to v0.12.0rc1.

**Comment by baiyu-123** [comment]
I'm use vllm-ascend v0.11.0rc1 and this error as follows：

INFO 12-23 09:07:54 [importing.py:63] Triton not installed or not compatible; certain GPU-related functions will not be available.
WARNING 12-23 09:07:57 [_custom_ops.py:20] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
Traceback (most recent call last):
  File "/usr/local/python3.11.13/bin/vllm", line 3, in <module>
    from vllm_omni.entrypoints.cli.main import main
  File "/vllm-workspace/vllm-omni/vllm_omni/__init__.py", line 23, in <module>
    from .config import OmniModelConfig
  File "/vllm-workspace/vllm-omni/vllm_omni/config/__init__.py", line 5, in <module>
    from vllm_omni.config.model import OmniModelConfig
  File "/vllm-workspace/vllm-omni/vllm_omni/config/model.py", line 9, in <module>
    from vllm.attention.backends.registry import AttentionBackendEnum
ModuleNotFoundError: No module named 'vllm.attention.backends.registry'
[ERROR] 2025-12-23-09:07:57 (PID:333, Device:-1, RankID:-1) ERR99999 UNKNOWN applicaiton exception

**Comment by gcanlin** [comment]
> I'm use vllm-ascend v0.11.0rc1 and this error as follows：
> 
> INFO 12-23 09:07:54 [importing.py:63] Triton not installed or not compatible; certain GPU-related functions will not be available. WARNING 12-23 09:07:57 [_custom_ops.py:20] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'") Traceback (most recent call last): File "/usr/local/python3.11.13/bin/vllm", line 3, in from vllm_omni.entrypoints.cli.main import main File "/vllm-workspace/vllm-omni/vllm_omni/**init**.py", line 23, in from .config import OmniModelConfig File "/vllm-workspace/vllm-omni/vllm_omni/config/**init**.py", line 5, in from vllm_omni.config.model import OmniModelConfig File "/vllm-workspace/vllm-omni/vllm_omni/config/model.py", line 9, in from vllm.attention.backends.registry import AttentionBackendEnum ModuleNotFoundError: No module named 'vllm.attention.backends.registry' [ERROR] 2025-12-23-09:07:57 (PID:333, Device:-1, RankID:-1) ERR99999 UNKNOWN applicaiton exception

Please use vllm-ascend v0.11.0rc2 and could you please show your newest commit in vllm-omni and more details about environment? It seems just an install issue instead of a bug. Or you can use vllm-omni `v0.11.0rc1` by the below command, which is static and we have validated it.
```
cd vllm-omni
git checkout v0.11.0rc1
```

**Comment by baiyu-123** [comment]
I'm use vllm-ascend v0.11.0rc2 and this error as follows：
INFO 12-23 09:45:42 [__init__.py:36] Available plugins for group vllm.platform_plugins:
INFO 12-23 09:45:42 [__init__.py:38] - ascend -> vllm_ascend:register
INFO 12-23 09:45:42 [__init__.py:41] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 12-23 09:45:42 [__init__.py:207] Platform plugin ascend is activated
INFO 12-23 09:45:47 [importing.py:63] Triton not installed or not compatible; certain GPU-related functions will not be available.
WARNING 12-23 09:45:49 [_custom_ops.py:20] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
Traceback (most recent call last):
  File "/usr/local/python3.11.13/bin/vllm", line 3, in <module>
    from vllm_omni.entrypoints.cli.main import main
  File "/vllm-workspace/vllm-omni/vllm_omni/__init__.py", line 23, in <module>
    from .config import OmniModelConfig
  File "/vllm-workspace/vllm-omni/vllm_omni/config/__init__.py", line 5, in <module>
    from vllm_omni.config.model import OmniModelConfig
  File "/vllm-workspace/vllm-omni/vllm_omni/config/model.py", line 9, in <module>
    from vllm.attention.backends.registry import AttentionBackendEnum
ModuleNotFoundError: No module named 'vllm.attention.backends.registry'
[ERROR] 2025-12-23-09:45:49 (PID:331, Device:-1, RankID:-1) ERR99999 UNKNOWN applicaiton exception

**Comment by baiyu-123** [comment]
"Added a `git checkout v0.11.0rc1`, the service is up now, the issue is resolved. Thanks a lot!"
