### ISSUE TITLE
[Bug]: qwen image 2512 oom on 4*5090 with -tp 4

### ISSUE THREAD

**Issue by JackLeeHal** [vllm-project/vllm-omni#919]
### Your current environment

<details>
<summary>running env</code></summary>
```docker run --runtime nvidia --gpus '"device=3,4,6,7"' \
    -v /data:/data \
    -p 8091:8091 \
    --ipc=host \
    vllm/vllm-omni:v0.14.0rc1 \
    vllm serve /data/Qwen/Qwen-Image-2512 --omni --vae-use-slicing --vae-use-tiling --gpu_memory_utilization 0.8 -tp 4 --port 8091```

WARNING 01-22 22:53:21 [mooncake_connector.py:18] Mooncake not available, MooncakeOmniConnector will not work
WARNING 01-22 22:53:22 [envs.py:194] Flash Attention library "flash_attn" not found, using pytorch attention implementation
INFO 01-22 22:53:23 [serve.py:60] Detected diffusion model: /data/Qwen/Qwen-Image-2512
(APIServer pid=1) INFO 01-22 22:53:23 [api_server.py:1272] vLLM API server version 0.14.0
(APIServer pid=1) INFO 01-22 22:53:23 [utils.py:263] non-default args: {'model_tag': '/data/Qwen/Qwen-Image-2512', 'port': 8091, 'model': '/data/Qwen/Qwen-Image-2512', 'tensor_parallel_size': 4, 'gpu_memory_utilization': 0.8}
(APIServer pid=1) INFO 01-22 22:53:23 [omni.py:126] Initializing stages for model: /data/Qwen/Qwen-Image-2512
(APIServer pid=1) INFO 01-22 22:53:23 [initialization.py:35] No OmniTransferConfig provided
(APIServer pid=1) INFO 01-22 22:53:23 [omni_stage.py:109] [OmniStage] stage_config: {'stage_id': 0, 'stage_type': 'diffusion', 'runtime': {'process': True, 'devices': '0,1,2,3', 'max_batch_size': 1}, 'engine_args': {'parallel_config': {'pipeline_parallel_size': 1, 'data_parallel_size': 1, 'tensor_parallel_size': 4, 'sequence_parallel_size': 1, 'ulysses_degree': 1, 'ring_degree': 1, 'cfg_parallel_size': 1}, 'vae_use_slicing': True, 'vae_use_tiling': True, 'cache_backend': 'none', 'cache_config': None, 'enable_cpu_offload': False, 'enforce_eager': False, 'model_stage': 'diffusion'}, 'final_output': True, 'final_output_type': 'image'}
(APIServer pid=1) INFO 01-22 22:53:23 [omni.py:318] [AsyncOrchestrator] Waiting for 1 stages to initialize (timeout: 60000s)
[Stage-0] WARNING 01-22 22:53:31 [mooncake_connector.py:18] Mooncake not available, MooncakeOmniConnector will not work
[Stage-0] WARNING 01-22 22:53:31 [envs.py:194] Flash Attention library "flash_attn" not found, using pytorch attention implementation
[Stage-0] INFO 01-22 22:53:52 [multiproc_executor.py:74] Starting server...
[Stage-0] WARNING 01-22 22:54:01 [mooncake_connector.py:18] Mooncake not available, MooncakeOmniConnector will not work
[Stage-0] WARNING 01-22 22:54:01 [mooncake_connector.py:18] Mooncake not available, MooncakeOmniConnector will not work
[Stage-0] WARNING 01-22 22:54:01 [mooncake_connector.py:18] Mooncake not available, MooncakeOmniConnector will not work
[Stage-0] WARNING 01-22 22:54:01 [mooncake_connector.py:18] Mooncake not available, MooncakeOmniConnector will not work
[Stage-0] WARNING 01-22 22:54:02 [envs.py:194] Flash Attention library "flash_attn" not found, using pytorch attention implementation
[Stage-0] WARNING 01-22 22:54:02 [envs.py:194] Flash Attention library "flash_attn" not found, using pytorch attention implementation
[Stage-0] WARNING 01-22 22:54:02 [envs.py:194] Flash Attention library "flash_attn" not found, using pytorch attention implementation
[Stage-0] WARNING 01-22 22:54:02 [envs.py:194] Flash Attention library "flash_attn" not found, using pytorch attention implementation
[Stage-0] INFO 01-22 22:54:03 [scheduler.py:229] Chunked prefill is enabled with max_num_batched_tokens=2048.
[Stage-0] INFO 01-22 22:54:03 [vllm.py:630] Asynchronous scheduling is enabled.
[Stage-0] INFO 01-22 22:54:03 [vllm.py:637] Disabling NCCL for DP synchronization when using async scheduling.
[Stage-0] INFO 01-22 22:54:04 [gpu_diffusion_worker.py:235] Worker 0 created result MessageQueue
[Stage-0] INFO 01-22 22:54:04 [scheduler.py:229] Chunked prefill is enabled with max_num_batched_tokens=2048.
[Stage-0] INFO 01-22 22:54:04 [vllm.py:630] Asynchronous scheduling is enabled.
[Stage-0] INFO 01-22 22:54:04 [vllm.py:637] Disabling NCCL for DP synchronization when using async scheduling.
[Stage-0] INFO 01-22 22:54:04 [scheduler.py:229] Chunked prefill is enabled with max_num_batched_tokens=2048.
[Stage-0] INFO 01-22 22:54:04 [vllm.py:630] Asynchronous scheduling is enabled.
[Stage-0] INFO 01-22 22:54:04 [vllm.py:637] Disabling NCCL for DP synchronization when using async scheduling.
[Stage-0] INFO 01-22 22:54:04 [scheduler.py:229] Chunked prefill is enabled with max_num_batched_tokens=2048.
[Stage-0] INFO 01-22 22:54:04 [vllm.py:630] Asynchronous scheduling is enabled.
[Stage-0] INFO 01-22 22:54:04 [vllm.py:637] Disabling NCCL for DP synchronization when using async scheduling.
[Gloo] Rank 0 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Gloo] Rank 1 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Gloo] Rank 3 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Gloo] Rank 2 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Stage-0] INFO 01-22 22:54:04 [gpu_diffusion_worker.py:91] Worker 0: Initialized device and distributed environment.
[Stage-0] INFO 01-22 22:54:04 [gpu_diffusion_worker.py:91] Worker 1: Initialized device and distributed environment.
[Stage-0] INFO 01-22 22:54:04 [gpu_diffusion_worker.py:91] Worker 3: Initialized device and distributed environment.
[Stage-0] INFO 01-22 22:54:04 [gpu_diffusion_worker.py:91] Worker 2: Initialized device and distributed environment.
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 2 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Gloo] Rank 1 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Stage-0] WARNING 01-22 22:54:04 [gpu_diffusion_model_runner.py:152] No OmniConnector config found, skipping initialization
[Stage-0] WARNING 01-22 22:54:04 [gpu_diffusion_model_runner.py:152] No OmniConnector config found, skipping initialization
[Gloo] Rank 0 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Gloo] Rank 3 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Stage-0] WARNING 01-22 22:54:04 [gpu_diffusion_model_runner.py:152] No OmniConnector config found, skipping initialization
[Stage-0] WARNING 01-22 22:54:04 [gpu_diffusion_model_runner.py:152] No OmniConnector config found, skipping initialization
Loading checkpoint shards: 100%|██████████| 4/4 [00:02<00:00,  1.50it/s]
Loading checkpoint shards: 100%|██████████| 4/4 [00:03<00:00,  1.31it/s]
Loading checkpoint shards: 100%|██████████| 4/4 [00:03<00:00,  1.25it/s]
Loading checkpoint shards: 100%|██████████| 4/4 [00:03<00:00,  1.22it/s]
Process DiffusionWorker-2:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 351, in worker_main
    worker_proc = WorkerProc(
                  ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 238, in __init__
    self.worker = self._create_worker(gpu_id, od_config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 244, in _create_worker
    return GPUDiffusionWorker(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 64, in __init__
    self.init_device()
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 110, in init_device
    self.model_runner.load_model(
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_model_runner.py", line 95, in load_model
    self.pipeline = model_loader.load_model(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/model_loader/diffusers_loader.py", line 202, in load_model
    model = initialize_model(od_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/registry.py", line 129, in initialize_model
    model = model_class(od_config=od_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/pipeline_qwen_image.py", line 279, in __init__
    self.transformer = QwenImageTransformer2DModel(od_config=od_config, **transformer_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/qwen_image_transformer.py", line 850, in __init__
    QwenImageTransformerBlock(
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/qwen_image_transformer.py", line 638, in __init__
    nn.Linear(dim, 6 * dim, bias=True),  # For scale, shift, gate for norm1 and norm2
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/linear.py", line 109, in __init__
    torch.empty((out_features, in_features), **factory_kwargs)
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_device.py", line 103, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU 2 has a total capacity of 31.36 GiB of which 108.75 MiB is free. Including non-PyTorch memory, this process has 31.24 GiB memory in use. Of the allocated memory 30.55 GiB is allocated by PyTorch, and 112.38 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Process DiffusionWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 351, in worker_main
    worker_proc = WorkerProc(
                  ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 238, in __init__
    self.worker = self._create_worker(gpu_id, od_config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 244, in _create_worker
    return GPUDiffusionWorker(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 64, in __init__
    self.init_device()
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 110, in init_device
    self.model_runner.load_model(
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_model_runner.py", line 95, in load_model
    self.pipeline = model_loader.load_model(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/model_loader/diffusers_loader.py", line 202, in load_model
    model = initialize_model(od_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/registry.py", line 129, in initialize_model
    model = model_class(od_config=od_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/pipeline_qwen_image.py", line 279, in __init__
    self.transformer = QwenImageTransformer2DModel(od_config=od_config, **transformer_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/qwen_image_transformer.py", line 850, in __init__
    QwenImageTransformerBlock(
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/qwen_image_transformer.py", line 638, in __init__
    nn.Linear(dim, 6 * dim, bias=True),  # For scale, shift, gate for norm1 and norm2
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/linear.py", line 109, in __init__
    torch.empty((out_features, in_features), **factory_kwargs)
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_device.py", line 103, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU 1 has a total capacity of 31.36 GiB of which 108.75 MiB is free. Including non-PyTorch memory, this process has 31.24 GiB memory in use. Of the allocated memory 30.55 GiB is allocated by PyTorch, and 112.38 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Process DiffusionWorker-3:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 351, in worker_main
    worker_proc = WorkerProc(
                  ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 238, in __init__
    self.worker = self._create_worker(gpu_id, od_config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 244, in _create_worker
    return GPUDiffusionWorker(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 64, in __init__
    self.init_device()
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 110, in init_device
    self.model_runner.load_model(
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_model_runner.py", line 95, in load_model
    self.pipeline = model_loader.load_model(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/model_loader/diffusers_loader.py", line 202, in load_model
    model = initialize_model(od_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/registry.py", line 129, in initialize_model
    model = model_class(od_config=od_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/pipeline_qwen_image.py", line 279, in __init__
    self.transformer = QwenImageTransformer2DModel(od_config=od_config, **transformer_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/qwen_image_transformer.py", line 850, in __init__
    QwenImageTransformerBlock(
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/qwen_image_transformer.py", line 638, in __init__
    nn.Linear(dim, 6 * dim, bias=True),  # For scale, shift, gate for norm1 and norm2
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/linear.py", line 109, in __init__
    torch.empty((out_features, in_features), **factory_kwargs)
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_device.py", line 103, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU 3 has a total capacity of 31.36 GiB of which 108.75 MiB is free. Including non-PyTorch memory, this process has 31.24 GiB memory in use. Of the allocated memory 30.55 GiB is allocated by PyTorch, and 112.38 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Process DiffusionWorker-0:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 351, in worker_main
    worker_proc = WorkerProc(
                  ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 238, in __init__
    self.worker = self._create_worker(gpu_id, od_config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 244, in _create_worker
    return GPUDiffusionWorker(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 64, in __init__
    self.init_device()
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 110, in init_device
    self.model_runner.load_model(
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_model_runner.py", line 95, in load_model
    self.pipeline = model_loader.load_model(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/model_loader/diffusers_loader.py", line 202, in load_model
    model = initialize_model(od_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/registry.py", line 129, in initialize_model
    model = model_class(od_config=od_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/pipeline_qwen_image.py", line 279, in __init__
    self.transformer = QwenImageTransformer2DModel(od_config=od_config, **transformer_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/qwen_image_transformer.py", line 850, in __init__
    QwenImageTransformerBlock(
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/qwen_image_transformer.py", line 638, in __init__
    nn.Linear(dim, 6 * dim, bias=True),  # For scale, shift, gate for norm1 and norm2
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/linear.py", line 109, in __init__
    torch.empty((out_features, in_features), **factory_kwargs)
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_device.py", line 103, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU 0 has a total capacity of 31.36 GiB of which 108.75 MiB is free. Including non-PyTorch memory, this process has 31.24 GiB memory in use. Of the allocated memory 30.55 GiB is allocated by PyTorch, and 112.38 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank0]:[W122 22:54:10.006219335 ProcessGroupNCCL.cpp:1524] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[Stage-0] ERROR 01-22 22:54:11 [multiproc_executor.py:115] Rank 0 scheduler is dead. Please check if there are relevant logs.
[Stage-0] ERROR 01-22 22:54:11 [multiproc_executor.py:117] Exit code: 1
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/entrypoints/omni_stage.py", line 1021, in _stage_worker_async_entry
    asyncio.run(_stage_worker_async(omni_stage, model, stage_payload, batch_timeout, stage_init_timeout))
  File "/usr/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/entrypoints/omni_stage.py", line 1221, in _stage_worker_async
    stage_engine = AsyncOmniDiffusion(
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/entrypoints/async_omni_diffusion.py", line 103, in __init__
    self.engine: DiffusionEngine = DiffusionEngine.make_engine(od_config)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/diffusion_engine.py", line 164, in make_engine
    return DiffusionEngine(config)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/diffusion_engine.py", line 47, in __init__
    self.executor = executor_class(od_config)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/executor/abstract.py", line 54, in __init__
    self._init_executor()
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/executor/multiproc_executor.py", line 60, in _init_executor
    processes, result_handle = self._launch_workers(broadcast_handle)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/executor/multiproc_executor.py", line 113, in _launch_workers
    data = reader.recv()
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 399, in _recv
    raise EOFError
EOFError

</details>


### Your code version

<details>
<summary>The commit id or version of vllm</summary>

```text
vllm/vllm-omni:v0.14.0rc1
```
</details>
<details>
<summary>The commit id or version of vllm-omni</summary>

```text
vllm/vllm-omni:v0.14.0rc1
```
</details>

### 🐛 Describe the bug

nvidia-smi
Fri Jan 23 15:13:00 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 575.51.03              Driver Version: 575.51.03      CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 5090        On  |   00000000:16:00.0 Off |                  N/A |
| 55%   27C    P1             52W /  575W |   23539MiB /  32607MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 5090        On  |   00000000:27:00.0 Off |                  N/A |
| 56%   23C    P8             20W /  575W |    4017MiB /  32607MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA GeForce RTX 5090        On  |   00000000:38:00.0 Off |                  N/A |
| 55%   28C    P1             68W /  575W |   10171MiB /  32607MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA GeForce RTX 5090        On  |   00000000:5A:00.0 Off |                  N/A |
| 55%   23C    P8             18W /  575W |       4MiB /  32607MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   4  NVIDIA GeForce RTX 5090        On  |   00000000:98:00.0 Off |                  N/A |
| 55%   23C    P8             19W /  575W |       4MiB /  32607MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   5  NVIDIA GeForce RTX 5090        On  |   00000000:A8:00.0 Off |                  N/A |
| 56%   23C    P8             17W /  575W |   28160MiB /  32607MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   6  NVIDIA GeForce RTX 5090        On  |   00000000:B8:00.0 Off |                  N/A |
| 56%   23C    P8             16W /  575W |       4MiB /  32607MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   7  NVIDIA GeForce RTX 5090        On  |   00000000:D8:00.0 Off |                  N/A |
| 55%   24C    P8             30W /  575W |       4MiB /  32607MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://vllm-omni.readthedocs.io), which can answer lots of frequently asked questions.

**Comment by david6666666** [comment]
Please add your startup command; you can refer to pr https://github.com/vllm-project/vllm-omni/pull/830

**Comment by JackLeeHal** [comment]
@david6666666  It's in running env : 
docker run --runtime nvidia --gpus '"device=3,4,6,7"' \ -v /data:/data \ -p 8091:8091 \ --ipc=host \ vllm/vllm-omni:v0.14.0rc1 \ vllm serve /data/Qwen/Qwen-Image-2512 --omni --vae-use-slicing --vae-use-tiling --gpu_memory_utilization 0.8 -tp 4 --port 8091

**Comment by david6666666** [comment]
requset command and log

**Comment by JackLeeHal** [comment]
command:

> docker run --runtime nvidia --gpus '"device=3,4,6,7"' \ -v /data:/data \ -p 8091:8091 \ --ipc=host \ vllm/vllm-omni:v0.14.0rc1 \ vllm serve /data/Qwen/Qwen-Image-2512 --omni --vae-use-slicing --vae-use-tiling --gpu_memory_utilization 0.8 -tp 4 --port 8091

log:

> WARNING 01-22 22:53:21 [mooncake_connector.py:18] Mooncake not available, MooncakeOmniConnector will not work
WARNING 01-22 22:53:22 [envs.py:194] Flash Attention library "flash_attn" not found, using pytorch attention implementation
INFO 01-22 22:53:23 [serve.py:60] Detected diffusion model: /data/Qwen/Qwen-Image-2512
(APIServer pid=1) INFO 01-22 22:53:23 [api_server.py:1272] vLLM API server version 0.14.0
(APIServer pid=1) INFO 01-22 22:53:23 [utils.py:263] non-default args: {'model_tag': '/data/Qwen/Qwen-Image-2512', 'port': 8091, 'model': '/data/Qwen/Qwen-Image-2512', 'tensor_parallel_size': 4, 'gpu_memory_utilization': 0.8}
(APIServer pid=1) INFO 01-22 22:53:23 [omni.py:126] Initializing stages for model: /data/Qwen/Qwen-Image-2512
(APIServer pid=1) INFO 01-22 22:53:23 [initialization.py:35] No OmniTransferConfig provided
(APIServer pid=1) INFO 01-22 22:53:23 [omni_stage.py:109] [OmniStage] stage_config: {'stage_id': 0, 'stage_type': 'diffusion', 'runtime': {'process': True, 'devices': '0,1,2,3', 'max_batch_size': 1}, 'engine_args': {'parallel_config': {'pipeline_parallel_size': 1, 'data_parallel_size': 1, 'tensor_parallel_size': 4, 'sequence_parallel_size': 1, 'ulysses_degree': 1, 'ring_degree': 1, 'cfg_parallel_size': 1}, 'vae_use_slicing': True, 'vae_use_tiling': True, 'cache_backend': 'none', 'cache_config': None, 'enable_cpu_offload': False, 'enforce_eager': False, 'model_stage': 'diffusion'}, 'final_output': True, 'final_output_type': 'image'}
(APIServer pid=1) INFO 01-22 22:53:23 [omni.py:318] [AsyncOrchestrator] Waiting for 1 stages to initialize (timeout: 60000s)
[Stage-0] WARNING 01-22 22:53:31 [mooncake_connector.py:18] Mooncake not available, MooncakeOmniConnector will not work
[Stage-0] WARNING 01-22 22:53:31 [envs.py:194] Flash Attention library "flash_attn" not found, using pytorch attention implementation
[Stage-0] INFO 01-22 22:53:52 [multiproc_executor.py:74] Starting server...
[Stage-0] WARNING 01-22 22:54:01 [mooncake_connector.py:18] Mooncake not available, MooncakeOmniConnector will not work
[Stage-0] WARNING 01-22 22:54:01 [mooncake_connector.py:18] Mooncake not available, MooncakeOmniConnector will not work
[Stage-0] WARNING 01-22 22:54:01 [mooncake_connector.py:18] Mooncake not available, MooncakeOmniConnector will not work
[Stage-0] WARNING 01-22 22:54:01 [mooncake_connector.py:18] Mooncake not available, MooncakeOmniConnector will not work
[Stage-0] WARNING 01-22 22:54:02 [envs.py:194] Flash Attention library "flash_attn" not found, using pytorch attention implementation
[Stage-0] WARNING 01-22 22:54:02 [envs.py:194] Flash Attention library "flash_attn" not found, using pytorch attention implementation
[Stage-0] WARNING 01-22 22:54:02 [envs.py:194] Flash Attention library "flash_attn" not found, using pytorch attention implementation
[Stage-0] WARNING 01-22 22:54:02 [envs.py:194] Flash Attention library "flash_attn" not found, using pytorch attention implementation
[Stage-0] INFO 01-22 22:54:03 [scheduler.py:229] Chunked prefill is enabled with max_num_batched_tokens=2048.
[Stage-0] INFO 01-22 22:54:03 [vllm.py:630] Asynchronous scheduling is enabled.
[Stage-0] INFO 01-22 22:54:03 [vllm.py:637] Disabling NCCL for DP synchronization when using async scheduling.
[Stage-0] INFO 01-22 22:54:04 [gpu_diffusion_worker.py:235] Worker 0 created result MessageQueue
[Stage-0] INFO 01-22 22:54:04 [scheduler.py:229] Chunked prefill is enabled with max_num_batched_tokens=2048.
[Stage-0] INFO 01-22 22:54:04 [vllm.py:630] Asynchronous scheduling is enabled.
[Stage-0] INFO 01-22 22:54:04 [vllm.py:637] Disabling NCCL for DP synchronization when using async scheduling.
[Stage-0] INFO 01-22 22:54:04 [scheduler.py:229] Chunked prefill is enabled with max_num_batched_tokens=2048.
[Stage-0] INFO 01-22 22:54:04 [vllm.py:630] Asynchronous scheduling is enabled.
[Stage-0] INFO 01-22 22:54:04 [vllm.py:637] Disabling NCCL for DP synchronization when using async scheduling.
[Stage-0] INFO 01-22 22:54:04 [scheduler.py:229] Chunked prefill is enabled with max_num_batched_tokens=2048.
[Stage-0] INFO 01-22 22:54:04 [vllm.py:630] Asynchronous scheduling is enabled.
[Stage-0] INFO 01-22 22:54:04 [vllm.py:637] Disabling NCCL for DP synchronization when using async scheduling.
[Gloo] Rank 0 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Gloo] Rank 1 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Gloo] Rank 3 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Gloo] Rank 2 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Stage-0] INFO 01-22 22:54:04 [gpu_diffusion_worker.py:91] Worker 0: Initialized device and distributed environment.
[Stage-0] INFO 01-22 22:54:04 [gpu_diffusion_worker.py:91] Worker 1: Initialized device and distributed environment.
[Stage-0] INFO 01-22 22:54:04 [gpu_diffusion_worker.py:91] Worker 3: Initialized device and distributed environment.
[Stage-0] INFO 01-22 22:54:04 [gpu_diffusion_worker.py:91] Worker 2: Initialized device and distributed environment.
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 2 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Gloo] Rank 1 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Stage-0] WARNING 01-22 22:54:04 [gpu_diffusion_model_runner.py:152] No OmniConnector config found, skipping initialization
[Stage-0] WARNING 01-22 22:54:04 [gpu_diffusion_model_runner.py:152] No OmniConnector config found, skipping initialization
[Gloo] Rank 0 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Gloo] Rank 3 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Stage-0] WARNING 01-22 22:54:04 [gpu_diffusion_model_runner.py:152] No OmniConnector config found, skipping initialization
[Stage-0] WARNING 01-22 22:54:04 [gpu_diffusion_model_runner.py:152] No OmniConnector config found, skipping initialization
Loading checkpoint shards: 100%|██████████| 4/4 [00:02<00:00, 1.50it/s]
Loading checkpoint shards: 100%|██████████| 4/4 [00:03<00:00, 1.31it/s]
Loading checkpoint shards: 100%|██████████| 4/4 [00:03<00:00, 1.25it/s]
Loading checkpoint shards: 100%|██████████| 4/4 [00:03<00:00, 1.22it/s]
Process DiffusionWorker-2:
Traceback (most recent call last):
File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 351, in worker_main
worker_proc = WorkerProc(
^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 238, in init
self.worker = self._create_worker(gpu_id, od_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 244, in _create_worker
return GPUDiffusionWorker(
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 64, in init
self.init_device()
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 110, in init_device
self.model_runner.load_model(
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_model_runner.py", line 95, in load_model
self.pipeline = model_loader.load_model(
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/model_loader/diffusers_loader.py", line 202, in load_model
model = initialize_model(od_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/registry.py", line 129, in initialize_model
model = model_class(od_config=od_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/pipeline_qwen_image.py", line 279, in init
self.transformer = QwenImageTransformer2DModel(od_config=od_config, **transformer_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/qwen_image_transformer.py", line 850, in init
QwenImageTransformerBlock(
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/qwen_image_transformer.py", line 638, in init
nn.Linear(dim, 6 * dim, bias=True), # For scale, shift, gate for norm1 and norm2
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/linear.py", line 109, in init
torch.empty((out_features, in_features), **factory_kwargs)
File "/usr/local/lib/python3.12/dist-packages/torch/utils/_device.py", line 103, in torch_function
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU 2 has a total capacity of 31.36 GiB of which 108.75 MiB is free. Including non-PyTorch memory, this process has 31.24 GiB memory in use. Of the allocated memory 30.55 GiB is allocated by PyTorch, and 112.38 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Process DiffusionWorker-1:
Traceback (most recent call last):
File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 351, in worker_main
worker_proc = WorkerProc(
^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 238, in init
self.worker = self._create_worker(gpu_id, od_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 244, in _create_worker
return GPUDiffusionWorker(
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 64, in init
self.init_device()
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 110, in init_device
self.model_runner.load_model(
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_model_runner.py", line 95, in load_model
self.pipeline = model_loader.load_model(
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/model_loader/diffusers_loader.py", line 202, in load_model
model = initialize_model(od_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/registry.py", line 129, in initialize_model
model = model_class(od_config=od_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/pipeline_qwen_image.py", line 279, in init
self.transformer = QwenImageTransformer2DModel(od_config=od_config, **transformer_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/qwen_image_transformer.py", line 850, in init
QwenImageTransformerBlock(
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/qwen_image_transformer.py", line 638, in init
nn.Linear(dim, 6 * dim, bias=True), # For scale, shift, gate for norm1 and norm2
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/linear.py", line 109, in init
torch.empty((out_features, in_features), **factory_kwargs)
File "/usr/local/lib/python3.12/dist-packages/torch/utils/_device.py", line 103, in torch_function
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU 1 has a total capacity of 31.36 GiB of which 108.75 MiB is free. Including non-PyTorch memory, this process has 31.24 GiB memory in use. Of the allocated memory 30.55 GiB is allocated by PyTorch, and 112.38 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Process DiffusionWorker-3:
Traceback (most recent call last):
File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 351, in worker_main
worker_proc = WorkerProc(
^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 238, in init
self.worker = self._create_worker(gpu_id, od_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 244, in _create_worker
return GPUDiffusionWorker(
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 64, in init
self.init_device()
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 110, in init_device
self.model_runner.load_model(
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_model_runner.py", line 95, in load_model
self.pipeline = model_loader.load_model(
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/model_loader/diffusers_loader.py", line 202, in load_model
model = initialize_model(od_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/registry.py", line 129, in initialize_model
model = model_class(od_config=od_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/pipeline_qwen_image.py", line 279, in init
self.transformer = QwenImageTransformer2DModel(od_config=od_config, **transformer_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/qwen_image_transformer.py", line 850, in init
QwenImageTransformerBlock(
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/qwen_image_transformer.py", line 638, in init
nn.Linear(dim, 6 * dim, bias=True), # For scale, shift, gate for norm1 and norm2
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/linear.py", line 109, in init
torch.empty((out_features, in_features), **factory_kwargs)
File "/usr/local/lib/python3.12/dist-packages/torch/utils/_device.py", line 103, in torch_function
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU 3 has a total capacity of 31.36 GiB of which 108.75 MiB is free. Including non-PyTorch memory, this process has 31.24 GiB memory in use. Of the allocated memory 30.55 GiB is allocated by PyTorch, and 112.38 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Process DiffusionWorker-0:
Traceback (most recent call last):
File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 351, in worker_main
worker_proc = WorkerProc(
^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 238, in init
self.worker = self._create_worker(gpu_id, od_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 244, in _create_worker
return GPUDiffusionWorker(
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 64, in init
self.init_device()
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_worker.py", line 110, in init_device
self.model_runner.load_model(
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/worker/gpu_diffusion_model_runner.py", line 95, in load_model
self.pipeline = model_loader.load_model(
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/model_loader/diffusers_loader.py", line 202, in load_model
model = initialize_model(od_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/registry.py", line 129, in initialize_model
model = model_class(od_config=od_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/pipeline_qwen_image.py", line 279, in init
self.transformer = QwenImageTransformer2DModel(od_config=od_config, **transformer_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/qwen_image_transformer.py", line 850, in init
QwenImageTransformerBlock(
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/models/qwen_image/qwen_image_transformer.py", line 638, in init
nn.Linear(dim, 6 * dim, bias=True), # For scale, shift, gate for norm1 and norm2
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/linear.py", line 109, in init
torch.empty((out_features, in_features), **factory_kwargs)
File "/usr/local/lib/python3.12/dist-packages/torch/utils/_device.py", line 103, in torch_function
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU 0 has a total capacity of 31.36 GiB of which 108.75 MiB is free. Including non-PyTorch memory, this process has 31.24 GiB memory in use. Of the allocated memory 30.55 GiB is allocated by PyTorch, and 112.38 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank0]:[W122 22:54:10.006219335 ProcessGroupNCCL.cpp:1524] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[Stage-0] ERROR 01-22 22:54:11 [multiproc_executor.py:115] Rank 0 scheduler is dead. Please check if there are relevant logs.
[Stage-0] ERROR 01-22 22:54:11 [multiproc_executor.py:117] Exit code: 1
Process SpawnProcess-1:
Traceback (most recent call last):
File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/entrypoints/omni_stage.py", line 1021, in _stage_worker_async_entry
asyncio.run(_stage_worker_async(omni_stage, model, stage_payload, batch_timeout, stage_init_timeout))
File "/usr/lib/python3.12/asyncio/runners.py", line 195, in run
return runner.run(main)
^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
return self._loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/entrypoints/omni_stage.py", line 1221, in _stage_worker_async
stage_engine = AsyncOmniDiffusion(
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/entrypoints/async_omni_diffusion.py", line 103, in init
self.engine: DiffusionEngine = DiffusionEngine.make_engine(od_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/diffusion_engine.py", line 164, in make_engine
return DiffusionEngine(config)
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/diffusion_engine.py", line 47, in init
self.executor = executor_class(od_config)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/executor/abstract.py", line 54, in init
self._init_executor()
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/executor/multiproc_executor.py", line 60, in _init_executor
processes, result_handle = self._launch_workers(broadcast_handle)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/vllm_omni/diffusion/executor/multiproc_executor.py", line 113, in _launch_workers
data = reader.recv()
^^^^^^^^^^^^^
File "/usr/lib/python3.12/multiprocessing/connection.py", line 250, in recv
buf = self._recv_bytes()
^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/multiprocessing/connection.py", line 430, in _recv_bytes
buf = self._recv(4)
^^^^^^^^^^^^^
File "/usr/lib/python3.12/multiprocessing/connection.py", line 399, in _recv
raise EOFError
EOFError

**Comment by david6666666** [comment]
I tested it locally with four A100-80G cards, and each card used about 37GB of GPU memory > 5090 32GB. @ZJY0516

**Comment by hsliuustc0106** [comment]
> I tested it locally with four A100-80G cards, and each card used about 37GB of GPU memory > 5090 32GB. [@ZJY0516](https://github.com/ZJY0516)

static memory consumption: 7~8B qwen-VL encoder (15GB) + 20B DiT-tp4 (10GB each) + vae (~1GB) ~ 26GB

@JackLeeHal I notice your command set gpu-utilization 0.8 * 32GB = 25.6GB < 26GB, so it will return OOM as expected. Currently the tp is not working for the encoders

**Comment by ZJY0516** [comment]
@JackLeeHal Could you please try cpu offloading? https://docs.vllm.ai/projects/vllm-omni/en/latest/user_guide/diffusion/cpu_offload_diffusion/

**Comment by JackLeeHal** [comment]
@hsliuustc0106  @david6666666 gpu-utilization not working for any value, but cpu offloading works for me, thanks guys. We can close this.

**Comment by ZJY0516** [comment]
yes, because `gpu-utilization` is designed for kv cache and diffusion model does nt need this
